---
title: "Clustering"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Clustering}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Setup
```{r setup}
library(multiAnalysis)
set.seed(123)
block_name <- "t_drugs"
hc_method <- "ward.D2"
hc_metric <- "spearman"
hc_index <- "silhouette"
k <- 2
n_boot <- 1000
MAX_CLUSTERS <- 10
colors_k <- get_colors()[seq(k) + 2]
```

# Data preparation
```{r formatting, eval = FALSE}
# Levels
row_annotation <- data.frame(Disease = disease)
names_levels <- levels(disease)

# names_levels <- c("Still", "Control", "SOJIA")

vars2 <- c("immun_aid_identifier", "weight", "height") # , "fatigue")
blocks <- blocks %>% select(
    -c(
        vars2,
        # ends_with("_global_assessment"),
        ends_with("_upper_limit_of_normal"),
        starts_with("max_"),
        "disease"
    )
)
# select(-c("eye_manifestations", "cardiac_manifestations")) # %>%
# select(-c("gender", "BMI", "age_at_inclusion_time", "batch"))
colnames(blocks) <- colnames(blocks) %>%
    tools::toTitleCase() %>%
    gsub("_", " ", .)
```

```{r}
if (block_name == "t_biol")
blocks <- blocks %>% select(starts_with("V1")) %>% set_colnames(colnames(.) %>% str_remove_all("V1\\.")) %>% select(-c(`Conjugated bilirubin`, `Neutrophils %`, `Erythrocyte sedimentation rate`, `ASAT ULN`, `Alk phosphatases ULN`, `Max CRP`, `Ferritin`, SAA, ends_with(" ULN")))

if (block_name == "t_aidai") {
  blocks <- apply(blocks, 2, function(x) (x == 0) %>% `!` %>% which() %>% length()) %>% `>`(2) %>% which() %>% select(blocks, .)
}

if (block_name %in% c("t_muscu", "t_drugs")) {
  blocks <- apply(blocks, 2, function(x) sum(x, na.rm = TRUE))  %>% `>`(2) %>% which() %>% select(blocks, .)
}
  
# Remove individuals with high levels of NA
res <- sapply(rownames(blocks), function(i) round((length(which(is.na(blocks[i, ]))) / ncol(blocks)) * 100, 1))
# names(res) <- clinic_intersect$immun_aid_identifier
plotHistogram(df = res, cex = 1.5) 
res0 <- sapply(rownames(blocks), function(i) (length(which(blocks[i, ] > 0))))
plotHistogram(df = res0, cex = 1.5, rows = ncol(blocks)) -> p
# list.map(list(2:4, 5:7, 8:ncol(blocks)), f(x) ~ {
#   sapply(rownames(blocks), function(i) (length(which(select(blocks, x)[i, ] > 0)))) %>%
#   plotHistogram(df = ., cex = 1.5, ratio = 7, rows = ncol(blocks))
# }) ->p2
#     plot_grid(
#         plotlist = c(list(p), p2),
#         align = "hv",
#         nrow = 1,
#         ncol = 4
#     )
# res1 <- sapply(rownames(blocks), function(i) (sum(blocks[i, ], na.rm = TRUE))) 
# plot_violin0(res1, colour = "red", size = 3, pch_colour = "black", pch_alpha = 0.5, title = "")
# name_inds <- names(res[res > 50])
# clinic_intersect %>% filter(str_detect(immun_aid_identifier, paste0("^", name_inds, "$", collapse = "|"))) %>% select(immun_aid_identifier, disease) -> temp
# name_lvls <- levels(clinic_intersect$disease)[unique(temp$disease) %>% sort()]
# table(temp$disease)
# res[res > 50]
if (block_name == "t_muscu") {
    # blocks <-  slice(blocks, -which(res0 < 2))
} else {
    blocks <- blocks[-which(res == 100), ]
}

res_scaled_na <- scale0(blocks, method = "minmax")

# if (block_name == "t_aidai") {
#   blocks[blocks == 0] <- NA
# }

# Scaling
res_scaled <- scale0(blocks)
```

# Optimal k
```{r, eval = FALSE}
get_clust_tendency(res_scaled, n = nrow(res_scaled) - 1)

index <- c(
    "kl", "ch", "hartigan", "cindex", "db", "silhouette", "duda", "pseudot2",
    "beale", "ratkowsky", "ball", "ptbiserial", "gap", "frey",
    "mcclain", "gamma", "gplus", "tau", "dunn", "hubert",
    "sdindex", "dindex", "sdbw", "all", "alllong"
)

res.nbclust <- NbClust(
    data = res_scaled,
    # diss = res_dist,
    min.nc = 2, max.nc = 10,
    method = hc_method,
    index = hc_index
)

# fviz_nbclust(res.nbclust)

# fviz_nbclust(
#     res_scaled,
#     get_clusters,
#     method = hc_index
# )
# (gaps <- clusGap(
#     res_scaled,
#     FUN = get_clusters,
#     K.max = 6,
#     B = n_boot
# ))
# fviz_gap_stat(gaps, maxSE = list(method = "Tibs2001SEmax", SE.factor = 1))
```

# Distance
```{r}
res_dist <- get_dist0(res_scaled, method = hc_metric)

# fviz_dist(
#     res_dist,
#     gradient = list(
#         low = colors_ind[1],
#         mid = colors_ind[2],
#         high = colors_ind[3]
#     )
# )
```

# Clustering
```{r}
# res_clus <- HCPC(pca_res, nb.clust = k, graph = FALSE)
# res_clus$data.clust$clust
# res_clus$desc.var$test.chi2

# group <- hclust(res_dist, method = hc_method) %>%
#     cutree(k = k)
# table(group, disease)

res_clus <- eclust(
    res_scaled,
    "hclust",
    hc_method = hc_method,
    stand = FALSE,
    hc_metric = hc_metric,
    k = k
)
table(res_clus$cluster, t(row_annotation))

res_clus_var <- res_scaled %>%
    t() %>%
    eclust(
        "hclust",
        hc_method = hc_method,
        stand = FALSE,
        hc_metric = hc_metric,
        k = k
    )
```

# Visualisation
```{r}
rownames(row_annotation) <- rownames(res_scaled)
n <- seq(length(names_levels))
row_col <- get_colors()[n]
names(row_col) <- names_levels %>% sort() %>% rev()

fviz_dend(
    res_clus,
    k = k,
    rect = TRUE,
    # rect_fill = TRUE,
    k_colors = colors_k,
    color_labels_by_k = TRUE,
)

t_scaled <- t(res_scaled)
t_scaled[is.na(t_scaled)] <- 0
res0 <- pvclust(
    t_scaled,
    method.hclust = hc_method,
    method.dist = "correlation",
    use.cor = "pairwise.complete.obs",
    nboot = n_boot,
    parallel = TRUE
) %>% suppressWarnings()
plot_dendrogram(res0, k = k, color = colors_k, row_col0)
# save_tiff(plot_dendrogram(res0, k = k), filename = "clust_tot.temp.tiff")

# print(res0, digits = 3)
# pvpick(res0)

# plot(res_clus, choice = "3D.map")

# plotDendrogram(2, row_dend0, res_scaled, MAX_CLUSTERS, cls[[k-1]])

fviz_cluster(
    res_clus,
    repel = TRUE,
    show.clust.cent = TRUE,
    palette = colors_k,
    ggtheme = theme_minimal(),
    main = "Factor map",
    ellipse.type = "norm"
) + theme_classic()

# dl <- dendlist(
#     color_dendrogram(d1, 2, get_colors()[c(3, 5) + 9]),
#     color_dendrogram(d2, 2, get_colors()[c(3, 5) + 9])
# )
# tanglegram(
#     dl,
#     # common_subtrees_color_lines = FALSE,
#     highlight_branches_lwd = FALSE,
#     highlight_distinct_edges = FALSE,
#     # k_branches = 2,
#     # k_labels = 2,
#     lwd = 2
# )
```

# Heatmap
```{r}
row_dend <- color_dendrogram(res_clus, k = k, colors = colors_k) %>% sort()
#     getMeanSilhouettePerPart() %>% which.max()
row_dend <- color_dendrogram(res_clus, k = 3, colors = colors_k) %>% sort()
col_dend <- color_dendrogram(res_clus_var, k = 2, colors = c("#f03088", "#d9d52c")) %>% sort()

codes <- attributes(clinic_intersect)$code %>% filter(str_detect(column_code, paste0("^", c("C_2643_3796", "C_2643_3803", "C_2649_3888", "C_2649_3895", "C_2649_3891", "C_2643_3797"), "$", collapse = "|"))) %>% pull(item_name) %>% c("batch") %>% select(clinic_intersect, .) %>% mutate(clinical_center = str_remove_all(clinical_center, "\\d{2} - ") %>% str_remove_all(" \\(.+\\)") %>% str_remove_all(".+ [-–] ")) %>% filter(str_detect(immun_aid_identifier, rownames(res_scaled_na) %>% paste0("^", ., "$", collapse = "|")))

heatmaply(
    res_scaled_na,
    # k_col = k,
    # k_row = k,
    colors = colors_ind,
    na.value = "black",
    # distfun = hc_metric,
    # hclust_method = hc_method,
    Rowv = row_dend,
    Colv = col_dend,
    # row_dend_left = TRUE
    # seriate = "mean",
    # col_side_colors = group_code,
    row_side_colors = row_annotation,
    row_side_palette = row_col,
    RowSideColors = disease,
    plot_method = "plotly",
    colorbar_xpos = 1.025,
    fontsize_row = 15,
    fontsize_col = 15,
    # na.rm = FALSE,
    key.title = "Disease"
    # side_color_layers,
) %>% layout(xaxis = list(ticklen = 0), yaxis2 = list(ticklen = 0))

ind_dist <- res_scaled %>%
    get_dist0(method = hc_metric)
row_dend0 <- ind_dist %>%
    hclust(method = hc_method)

col_dist <- res_scaled %>%
    t() %>%
    get_dist0(method = hc_metric)
col_dend0 <- col_dist %>%
    hclust(method = hc_method)

pheatmap(
    res_scaled_na,
    color = colorRampPalette(colors_ind)(100),
    angle_col = 315,
    na_col = "white",
    annotation_row = row_annotation,
    border_color = NA,
    annotation_colors = list(Disease = row_col),
    # annotation_col = my_sample_col,
    cluster_rows = row_dend0,
    cluster_cols = col_dend0,
    cutree_rows = k,
    cutree_cols = k,
    fontsize = 12
)

heatmap(
    as.matrix(res_scaled_na),
    col = colorRampPalette(colors_ind)(100),
    scale = "none",
    na.rm = FALSE,
    # na_col = "black",
    RowSideColors = row_col0,
    Rowv = row_dend,
    Colv = col_dend
)

# clinic_intersect %>% filter(str_detect(disease, "control")) %>%
#     arrange(immun_aid_identifier)
```

# Quality
```{r}
# plotGapPerPart(gaps, MAX_CLUSTERS)
plotFusionLevels(MAX_CLUSTERS, row_dend0)
cls <- getClusterPerPart(MAX_CLUSTERS, col_dend0)
get_summary(col_dist, cls, MAX_CLUSTERS, col_dend0, k = k) %>% kable0()
vars <- list.map(seq(k), f(i) ~ cl[cl == i] %>% names())
cls <- getClusterPerPart(MAX_CLUSTERS, row_dend0)
get_summary(ind_dist, cls, MAX_CLUSTERS, row_dend0, k = k) %>% kable0()
plot_silhouette0(res_dist, cls, k, colors_k = get_colors()[c(3, 5)])
# plot_silhouette0(res_dist, cls, k, colors_k = c(get_colors()[c(5, 3)], alpha("#FF7F00", alpha = 0.5)))

lapply(vars, function(x) get_genes_path(enriched[[2]][[i]][-3], x, detect = "Genes", name = "Term") %>% suppressMessages()) -> cou
lapply(cou, function(x) lapply(x, function(y) lapply(name_immu, function(x) grepl(x, y, ignore.case = TRUE) %>% any()) %>% as.numeric() %>% as.data.frame() ) %>% list_cbind() %>% set_rownames(name_immu) %>% apply(1, sum) %>% sort(TRUE) %>% .[. != 0]) -> cou0
cou1 <- lapply(seq(cou0), function(x) cou0[[x]] / length(vars[[x]]) %>% `/`(100))
lapply(cou1, function(x) round(x) %>% .[.>= 20])
sapply(cou, length)

lapply(cou, function(x) lapply(x, function(y) lapply(name_immu, function(x) grepl(x, y, ignore.case = TRUE) %>% any()) %>% as.numeric() %>% as.data.frame()  %>% as.data.frame() )%>% list_cbind()  %>% set_rownames(name_immu)) %>% list_cbind() %>% apply(1, sum) %>% sort(TRUE) %>% .[. != 0] / 15

# list.map(cou, f(i) ~ getDistPerVariable0(res_scaled, cls[[k - 1]]) %>% `/`(100) %>% as.data.frame() %>% select(i) %>% apply(1, mean)) %>% Reduce(rbind, .) %>% set_rownames(names(cou)) %>% round() %>% rbind(N = cou2) %>% kable0()

# Variable contribution
100 * getCtrVar(k, cls[[k - 1]], res_scaled)
ctr <- getDiscriminantVariables(k, cls[[k - 1]], res_scaled, ncol(res_scaled))
vars <- head(ctr, 15) %>% rownames()
# rownames(ctr) <- str_sub(rownames(ctr), 1, 40) %>% to_any_case(unique_sep = NULL, parsing_option = 3)
plotHistogram(df = ctr, cex = 1.5, dec = 0, ratio = 4, n = 15)
GimmeMyPlot::plot_bar(
    select(ctr, 1),
    n_max = 15,
    digits = 1,
    threshold = 0,
    abs = TRUE,
    colour = c("#99000D", "gray"),
    title = ".",
    label_x = "value",
    # colour_text = "black",
    width_text = 25
)
# plot_bar(select(ctr, 1), n = 15)
# round(ctr[, 1, drop = FALSE], 2)

# x = blocks; res = sapply(seq(nrow(x)), function(i) round((length(which(is.na(x[i, ]))) / ncol(x))*100, 1))
#  names(res) <- rownames(blocks[[1]])
# plotHistogram(df = res, hjust = -0.4) +
#     geom_hline(yintercept = c(35), col = "red")

y[, 1] %>% set_names(rownames(y)) -> Y
cl <- cls[[k - 1]]
# as.factor(as.matrix(disease)) %>% set_names(row.names(blocks11[[1]])) -> Y
factor(cl, labels = c(Y[cl == 1] %>% typical(), Y[cl == 2] %>% typical())) %>% confusionMatrix(as.factor(Y), positive = "SD") -> tmp; list(tmp$table, c(tmp$overall[1], tmp$byClass[seq(2)]) %>% round(2))
Y[cl == 1] %>% .[. == "Control"]
n <- 6

(table(Y)[1])

table(cl)
sapply(unique(cl), function(i) Y[cl == i] %>% typical())
lapply(unique(cl), function(i) Y[cl == i] %>% table())
sapply(unique(cl), function(i) Y[cl == i] %>% .[. != typical(.)])
lapply(unique(cl), function(i) Y[cl == i] %>% table()) -> tmp0; 

cl[cl == 4] <- 1
tmp0(c(1, 2, ))

n_levels <- c("SD", "SAID", "HV")
cl0 <- factor(cl, labels = n_levels)
Y0 <- mapply(function(x, y) rep(x, y), n_levels, unique(table(cl))) %>% unlist() %>% factor()
confusionMatrix(cl0, Y0) -> tmp
tmp$overall[1] %>% round(2)
tmp$byClass[seq(3), seq(2)] %>% round(2) %>% as.data.frame() %>% set_rownames(rownames(.) %>% str_remove_all("Class\\: "))

col_kable<- function(k, x, i) {
  n <- sum(x[, i])
  k %>% column_spec(i+1, background =  colorRampPalette(c("white", "black"))(n)[x[, i]], color = ifelse(x[, i]/n > 0.5, "white", "black"))
}

# cf <- 
# kbl(tmp$table, escape = FALSE, align = "c") %>%
#     kable_minimal(full_width = FALSE) %>%
#     col_kable(tmp$table, 1) %>%
#     col_kable(tmp$table, 2) %>%
#     col_kable(tmp$table, 3) %>%
#     column_spec(1, bold = TRUE, color = row_col) %>%
#     footnote(general  = paste0("Accuracy: ", tmp$overall[1] %>% round(2)))
#%>%
  # row_spec(0, bold = TRUE, color = row_col)

kable(tmp$table, align = "c") %>%
    kable_styling(full_width = F, stripe_color  = "white") %>%
    col_kable(tmp$table, 1) %>%
    col_kable(tmp$table, 2) %>%
    col_kable(tmp$table, 3) %>%
    column_spec(1, bold = TRUE, color = row_col) %>%
    row_spec(0:3, extra_css = "border-bottom-style: none; border-top-style: none") #%>%
    # footnote(tmp$overall[1] %>% round(2), general_title = "Accuracy: ",  footnote_as_chunk = TRUE, title_format = c("underline")) 

kbl(tmp$byClass[seq(3), seq(2)] %>% round(2) %>% as.data.frame() %>% set_rownames(rownames(.) %>% str_remove_all("Class\\: ")), align = "c") %>%
  kable_minimal(full_width = FALSE) %>%
column_spec(1, bold = TRUE, color = row_col)  %>%
    row_spec(0:3, extra_css = "border-bottom-style: none; border-top-style: none") 

# blocks0 <- blocks
# var <- c("alat", "asat", "ggt")
# colnames(blocks0) <- to_any_case(colnames(blocks0), unique_sep = NULL, parsing_option = 3)
# colnames(blocks0)[colnames(blocks0) %in% var] <- toupper(var)

stats <- as.data.frame(blocks) %>%
    cbind(cl = as.character(cl)) %>%
    calculate_test1(method = "kruskal") %>% 
    arrange(p)
filter(stats, p <= 0.05) %>% select(-c(" ")) %>% kable0()
filter(stats, p <= 0.05) %>% pull(Variables) %>% list.map(f(x) ~ select(blocks, x) %>% mutate(cl = cl) %>% group_by(cl) %>% group_split() %>% as.list() %>% list.map(f(i) ~ pull(i, x)) %>% list_cbind() %>% set_colnames(paste0("G", seq(length(unique(cl))))) %>% plot_violin0(method = "kruskal", colour = get_colors()[seq(length(unique(cl)))], size = 3, pch_colour = "black", pch_alpha = 0.5, ylab = x, title = "", wrap = 10)) %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 2,
        ncol = 3
    )

filter(stats, p <= 0.05) %>% pull(Variables) %>% list.map(f(x, y, z) ~ select(blocks, x) %>% mutate(cl = cl) %>% set_colnames(c("name", "cl")) %>% dunn_test(name ~ cl, p.adjust.method = "BH") %>% filter(p <= .05))

filter(stats, p <= 0.05) %>% pull(Variables) %>% list.map(f(x) ~ select(blocks, x) %>% mutate(cl = cl) %>% group_by(cl) %>% group_split() %>% as.list() %>% list.map(f(i) ~ pull(i, x)) %>% list_cbind() %>% set_colnames(paste0("G", seq(3))) %>% get_melt() %>% dunn_test(value ~ name, p.adjust.method = "BH") %>% add_xy_position(x = "group"))

fct_count(as.factor(cl))
cl <- cl[cl %in% c(1, 3)]
cl0 <- data.frame(cl) %>% rownames_to_column("immun_aid_identifier") %>% mutate(cl = as.character(cl), immun_aid_identifier = as.double(immun_aid_identifier))

blocks00 <- as.data.frame(clinic_transf) %>% mutate(`Age at diagnosis` = interval(birth, date_of_the_first_disease_symptom) / years(1))

# %>% mutate(immun_aid_identifier = rownames(.) %>% as.double())

data("t_biol")
data("t_general")
data("t_aidai")
t_biol0 <- t_biol %>% select(starts_with("V1")) %>% set_colnames(colnames(.) %>% str_remove("V1.")) %>% mutate(immun_aid_identifier = rownames(.) %>% as.double()) %>% select(-c(`Serum peak`, Schizocytes, SAA)) # %>% select(-c("Conjugated bilirubin", "Max CRP", "Triglycerides", "LDH", "Glycosylated ferritin", "Ferritin"))
t_general0 <- t_general %>% mutate(immun_aid_identifier = rownames(.) %>% as.double()) %>% select(-c("Fever", "Frequency if flares/attacks"))  %>% left_join(select(blocks00, age_at_inclusion_time, `Age at diagnosis`, BMI, immun_aid_identifier)) %>% rename(`Age at inclusion` = age_at_inclusion_time) # %>% select(-c(`In how many months?`, `Weight loss (kg)`))
t_aidai0 <- t_aidai %>% mutate(`Total score` = rowSums(., na.rm = TRUE)) %>% mutate(immun_aid_identifier = rownames(.) %>% as.double()) %>% select(-c(`Eye manifestations`, `Neurological manifestations`, `Vascular involvement`)) # %>% select(-c("Ear-Nose-Throat symptoms", "Cardiac manifestations", "Painful nodes", "Chest pain", "Headaches", "Diarrhea")) 
t_cyt0 <- t_cyt %>% mutate(immun_aid_identifier = rownames(.) %>% str_remove_all("A.") %>% as.double()) %>% update_columns(seq(ncol(.)), function(x) as.double(x))

t_all <- list(t_biol0, t_general0, t_aidai0, t_cyt0, t_cyt1) %>% Reduce(function(x, y) full_join(x, y), .) # %>% select( c(vars, "immun_aid_identifier"))

data("t_treat_types")
data("t_treat_subtypes")
data("t_manifs")
data("t_muscu")
data("t_muco")
# t_manif0 <- t_manifs %>% mutate(immun_aid_identifier = rownames(.) %>% as.double())
t_treat <- left_join(
  as.data.frame(t_treat_types) %>% mutate(immun_aid_identifier = rownames(.) %>% as.double()),
  as.data.frame(t_treat_subtypes) %>% mutate(immun_aid_identifier = rownames(.) %>% as.double()) %>% rename(`Other biological` = Other)
) %>% update_columns(str_which(colnames(.), "identifier", TRUE), function(x) as.character(x))
t_muscu0 <- t_muscu %>% mutate(immun_aid_identifier = rownames(.) %>% as.double()) %>% update_columns(str_which(colnames(.), "identifier", TRUE), function(x) as.character(x))
# %>% select(colnames(t_treat_types)[1])

blocks0 <-  select(blocks00, "immun_aid_identifier") %>% full_join(t_general0) %>% select(colnames(t_all))

vars <- c("Physician global assessment", "Max (°C)", "Bone pain", "NK cell", "Neutrophils", "Monocyte non-conventional", "CRP", "IL2", "IFNG")
# vars <- c("Neutrophils %", "CRP",  "Leucocytes", "Fatigue", "Dermatological manifestations", "Chest pain")
vars <- c("Neutrophils %", "T cell CD4+ naive", "T cell CD8+ memory", "CRP", "M score", "Fatigue")
blocks0 <- as.data.frame(t_all) %>%
    right_join(cl0) %>% 
    column_to_rownames("immun_aid_identifier")

stats <- calculate_test1(blocks0, method = "wilcox", stats = TRUE) %>%
  filter(p <= 0.2)

pivot_longer(x, !cl) %>%
    group_by(name, cl) %>%
    summarize(stat = print_stats0(value)) %>%
    ungroup() %>%
    spread(cl, stat) %>%
    set_colnames(c("Variables", unique(cl) %>% length() %>% seq() %>% paste0("G", .))) %>%
    left_join(stats)

select(stats, -c("W", "FDR")) %>%
  kable0()

# colour_var <- get_colors()[-c(6:7)]
colour_var <- colorRampPalette(
  c(brewer.pal(9, "YlOrBr")[4:7],
    brewer.pal(9, "RdBu")[1:3],
    brewer.pal(11, "PiYG")[4:1],
    brewer.pal(11, "PRGn")[1:4],
    brewer.pal(11, "RdYlBu")[8:11],
    brewer.pal(11, "BrBG")[10:8],
    brewer.pal(11, "PiYG")[8:11]
    )
  )(nrow(stats))

list.map(
    # colnames(select(blocks0, -cl)) %>% discard(function(x) str_detect(x, "ULN")),
    # pull(stats, Variables),
    vars,
    f(x, y) ~ {
        select(blocks0, c(x, cl)) %>% 
            group_by(cl) %>% 
            group_split() %>% 
            as.list() %>% 
            list.map(f(i) ~ pull(i, x)) %>% 
            list_cbind() %>% 
            set_colnames(paste0("G", seq(length(unique(cl))))) %>% 
            plot_violin0(
                method = "wilcox",
                # colour = get_colors()[seq(length(unique(cl)))],
                # colour = c(colour_var[y], alpha(colour_var[y], 0.5)),
                colour = brewer.pal(12, "Paired")[4:3],
                color_title = "black",
                wrap = 7,
                wrap_title = 50,
                size = 3,
                pch_colour = "gray50",
                pch_alpha = 0.5,
                ylab = "",
                title = str_remove_all(x, "( (non-)?conventional)|( global)") %>% str_replace_all("Max \\(°C\\)", "Fever")
            ) + theme(axis.title.y = element_blank())
    }
) %>%
    plot_grid(
        plotlist = .,
        # align = "hv",
        nrow = 3,
        ncol = 4
    )



vars <- c("batch", "gender", "patient_ethnicity") #, "age_at_inclusion_time")
blocks0 <- left_join(blocks00, select(clinic_transf, c(vars, immun_aid_identifier))) %>% 
  select(c(vars, "immun_aid_identifier")) %>% 
  mutate(
    batch = as.factor(batch),
    # age_at_inclusion_time = ifelse(age_at_inclusion_time >= 18, "Adult", "Children")
  )
blocks0 <- as.data.frame(t_muscu0) %>%
    right_join(cl0) %>% 
    column_to_rownames("immun_aid_identifier")
blocks0 <- blocks0 %>%
  # filter(!is.na(batch)) %>% 
  # na.omit() %>%
  update_columns(seq(ncol(.)), function(x) ifelse(is.na(x), 0, x)) %>%
  remove_constant() %>%
  select(update_columns(., seq(ncol(.)), function(x) as.numeric(x)) %>% colSums() %>% `>`(1) %>% which()) %>%
  rename(Cluster = cl)
stats <- chi2_test(pull(blocks0, Cluster), select(blocks0, -Cluster), method = "fisher")

list.map(
  select(blocks0, -Cluster) %>% colnames(),
  f(i) ~ {
    select(blocks0, c(i, Cluster)) %>%
      chi_plot(method = "fisher", colour1 = c(get_colors()[c(1, 3)], brewer.pal(9, "Pastel1")[c(1, 3)]), title = i, wrap = 50, cex_main = 21, cex_sub = 15, cex = 0.28) +
      theme(
        legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_blank()
      ) 
  }
) %>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 3,
        ncol = 3
    )



confonding <- list.map(
  select(blocks0, -c("Max (°C)", "Number of consecutive days")),
  cor_test0(blocks, ., method = "spearman") %>% print_cor() %>% filter(p <= 0.05)
)

list.map(
  rownames(confonding$`Age at inclusion time`),
f(x, y) ~ plot_cor2(data_frame(pull(blocks, x), pull(blocks0, "Age at inclusion time")) %>% set_colnames(c(x, "Age at inclusion time")), method = "spearman", color = get_colors()[-c(6, 7)][y])
)%>%
    plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 2,
        ncol = 3
    )



plot_mean_test(dat, "physician_global_assessment", as_tibble(stats), colors_k)

n <- 8
(descr <- pivot_longer(dat, !cl) %>%
    group_by(name, cl) %>%
    summarise(
        mean = mean(value, na.rm = TRUE),
        sd = sd(value, na.rm = TRUE),
        n = length(which(!is.na(value)))
    ) %>%
    # filter(str_detect(name, paste(names(var0), collapse= "|")))  %>%
    pivot_wider(names_from = cl, values_from = c(mean, sd, n))
)

stats %>%
    as_tibble() %>%
    arrange(p) %>%
    filter(p < 0.05) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance(p.col = "p.adj")

# for (i in as.data.frame(vars)[-c(7, 11, 12), 1]) group_by((data.frame(x = dat[, i], cl)), cl) %>% mutate(log_d = (x)) %>% shapiro_test(x) %>% print()

ctr2 <- tibble(name = rownames(ctr), ctr = ctr[, 1])
stats2 <- stats %>%
    as_tibble() %>%
    select(all_of(c("name", "p", "p.signif")))
tot <- Reduce(left_join, list(ctr2, descr, stats2)) # %>% arrange(p)
tot <- tot %>%
    filter(p < 0.05) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance(p.col = "p.adj")
tot$p <- format(tot$p, scientific = TRUE, digits = 2)
tot$p.adj <- format(tot$p.adj, scientific = TRUE, digits = 2)
arrange(tot, desc(ctr)) %>%
    # slice(seq(n)) %>%
    select(-c(starts_with("n_"), contains("sd_"), "p", "p.signif"))


  
  
list.map(
 vars, 
  f(x, xtt, xt) ~ {
    pull(x, Variables) %>% list.map(
      f(y) ~ {
select(blocks, y) %>% mutate(cl = pull(t_conf, xt)) %>% group_by(cl) %>% group_split() %>% as.list() %>% list.map(f(i) ~ pull(i, 1)) %>% list_cbind() %>% set_colnames(pull(t_conf, xt) %>% levels()) %>% plot_violin0(method = "wilcox", colour = sapply(c(25, 75), function(j) col2hcl(get_colors()[xtt], l = j)), size = 3, pch_colour = "black", ylab = y, pch_alpha = 0.5, title = "", wrap = 10)
})
}) -> p
plot_grid(
    plotlist = c(p[[1]], list(NULL), p[[2]]),
    align = "hv",
    nrow = 2,
    ncol = 4
)

confonding1 <- list.map(
  select(t_conf, -1),
  f(i) ~ as.data.frame(blocks) %>%
      cbind(cl = as.character(i)) %>%
      calculate_test1(method = "wilcox") %>% 
      arrange(p) %>%
    filter(p <= 0.05)
)
# pairwise_fisher_test(table(tab))

list.map(
  confonding1[1:2], 
  f(x, xtt, xt) ~ {
    pull(x, Variables) %>% list.map(
      f(y) ~ {
select(blocks, y) %>% mutate(cl = pull(t_conf, xt)) %>% group_by(cl) %>% group_split() %>% as.list() %>% list.map(f(i) ~ pull(i, 1)) %>% list_cbind() %>% set_colnames(pull(t_conf, xt) %>% levels()) %>% plot_violin0(method = "wilcox", colour = sapply(c(25, 75), function(j) col2hcl(get_colors()[xtt], l = j)), size = 3, pch_colour = "black", ylab = y, pch_alpha = 0.5, title = "", wrap = 10)
})
}) -> p
plot_grid(
    plotlist = c(p[[1]], list(NULL), p[[2]]),
    align = "hv",
    nrow = 2,
    ncol = 4
)
    
confonding1[[4]] <- as.data.frame(blocks[-19, ]) %>%
  cbind(cl = as.character(pull(t_conf, batch)[-19])) %>%
  calculate_test1(method = "wilcox") %>% 
  arrange(p) %>%
  filter(p <= 0.05)

pull(confonding1[[4]], Variables) %>% list.map(
      f(y) ~ {
select(blocks[-19, ], y) %>% mutate(cl = pull(t_conf, batch)[-19]) %>% group_by(cl) %>% group_split() %>% as.list() %>% list.map(f(i) ~ pull(i, 1)) %>% list_cbind() %>% set_colnames(paste0("Batch", c(2, 3))) %>% plot_violin0(method = "wilcox", colour = c(get_colors()[3], alpha(get_colors()[3],  alpha = 0.25)), size = 3, pch_colour = "black", ylab = y, pch_alpha = 0.5, title = "", wrap = 10)
}) %>%
  plot_grid(
        plotlist = .,
        align = "hv",
        nrow = 1,
        ncol = 3
    )

confonding0 <- list.map(
  vars[-1], 
f(i) ~ as.data.frame(blocks) %>%
    cbind(cl = as.character(pull(tab, i))) %>%
    calculate_test1(method = "wilcox") %>% 
    arrange(p) %>%
  filter(p <= 0.05)
)

as.data.frame(blocks[-19, ]) %>%
    cbind(cl = as.character(pull(tab, 1)[-19])) %>%
    calculate_test1(method = "wilcox") %>% 
    arrange(p) %>%
    filter(p <= 0.05) %>% kable0()

plotHistogram(df = ctr) +
    labs(subtitle = expression(paste("Fisher test for count data (2,32), ", italic("p"), " = ", "<0.0001"))) +
    theme(plot.subtitle = element_text(size = 15, hjust = 0.5, face = "italic", color = "black"))

# Outputs
# write.csv2(as.data.frame(cl), "clusters.temp.tsv")
```

# NHC
```{r}
classif <- getClassif(2, MAX_CLUSTERS, res_scaled, res_dist)
# res_dist0 <- get_dist(res_scaled, stand = FALSE, method = "euclidian")
# classif <- lapply(2:MAX_CLUSTERS, function(i) pam(res_dist0, i, diss = TRUE))
classif[[k]]$data <- res_scaled
cls <- getClusterPerPart(MAX_CLUSTERS, classif)
get_summary(res_dist, cls, MAX_CLUSTERS, k = k)

fviz_cluster(
    classif[[k]],
    data = res_scaled,
    repel = TRUE,
    show.clust.cent = TRUE,
    palette = colors_k,
    ggtheme = theme_minimal(),
    main = "Factor map",
    ellipse.type = "norm"
) + theme_classic()
```
