---
title: "DSeq2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DSeq2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(multiAnalysis)
library(tximport)
library(rhdf5)
# Load matrix for treatment
set_analysis(block_name = "emna_treat", type = "qual")
# set_analysis(block_name = "still_manif", type = "qual")
# Extract variable for discrimination
batches <- clinic_intersect$batch %>% set_names(row.names(clinic_intersect))

if (!file.exists(file.path(path_img, "shrinked"))) {
      dir.create(file.path(path_img, "shrinked"))
  }
```

```{r setup}
setEnrichrSite("Enrichr")
# listEnrichrDbs()$libraryName[listEnrichrDbs()$libraryName %>% grepl("orphanet", ., ignore.case = TRUE)]
dbs <- c("GO_Molecular_Function_2021", "GO_Biological_Process_2021", "Orphanet_Augmented_2021", "WikiPathway_2021_Human", "MSigDB_Hallmark_2020", "Reactome_2022")
```

```{r}
# Load the count matrix
path <- file.path(golem::get_golem_wd(), "inst", "extdata")
processed_matrix <- read_tsv(file = file.path(path, "processed_gene_matrix.tsv"))
counts_matrix <- read_delim(file = file.path(path, "raw_gene_matrix.txt"), delim = " ", skip = 1, col_names = colnames(processed_matrix))
```

```{r, eval = FALSE}
transcript_counts <- list.map(
    seq(3),
    f(i) ~ {
        list.map(
            list.files(
                path = file.path(path, "RNASeq", "transcript_counts", paste0("Batch", i)),
                full.names = TRUE,
                pattern = "tsv"
            ),
            f(i) ~ {
                read_tsv(i) %>%
                    select(target_id, est_counts) %>%
                    set_colnames(c("id", str_extract(i, "\\d{5}[AB]05PB1")))
            }
        ) %>% Reduce(function(x, y) full_join(x, y, by = "id"), .)
    }
) %>% Reduce(function(x, y) full_join(x, y, by = "id"), .)
# use_data(transcript_counts, overwrite = TRUE)
```
```{r, eval = FALSE}
kallisto_files0 <- list.map(
    c("First", "Second", "Third"),
    f(i) ~ {
        list.map(
            list.files(
                path = file.path(path, "kallisto", paste0(i, "Batch_h5files")),
                full.names = TRUE,
                pattern = "h5"
            ), f(i) ~ {
                tmp <- H5Fopen(i)
                # h5closeAll()
                data.frame(tmp$est_counts) %>% set_colnames(c(str_extract(i, "\\d{5}[AB]05PB1")))
            }
        ) %>% Reduce(cbind, .)
    }
) %>% Reduce(cbind, .)
```

```{r, eval = FALSE}
tr_files <- list.map(
    seq(3),
    f(i) ~ {
        list.files(
            path = file.path(path, "RNASeq", "transcript_counts", paste0("Batch", i)),
            full.names = TRUE,
            pattern = "tsv"
        )
    }
) %>% unlist()
tr_names <- read_tsv(tr_files[1])$target_id %>% str_remove_all("\\.*")
gene_query <- getBM(
    attributes = c("ensembl_transcript_id", "hgnc_symbol"),
    mart = db_annot
)
tximport(., ignoreTxVersion = TRUE, type = "kallisto", txOut = TRUE, tx2gene = tx2gene, ignoreAfterBar = TRUE)
```

```{r}
# counts_matrix <- transcript_counts
# Split the visits
l_visits <- list.map(
    c("A", "B"),
    f(i) ~ {
        str_detect(colnames(counts_matrix), paste0("^(\\d{5})", i)) %>%
            which() %>%
            c(1, .) %>%
            select(counts_matrix, .)
    }
)

# Formatting the patient names
col_names <- list.map(l_visits, f(.) ~ {
    colnames(.) %>%
        str_remove_all("(A|B)05PB1") %>%
        as.numeric() %>%
        sort()
})

# Select visit A, rename columns, order by patient ID
l_visits <- list.map(
    c("A", "B"),
    f(i) ~ {
        set_colnames(l_visits[[i]], colnames(l_visits[[i]]) %>% str_replace_all(paste0("0?(\\d{4})(A|B)05PB1"), "\\1")) %>%
            select(c("GeneName", as.character(col_names[[i]])))
    }
)
counts_matrix <- l_visits[["A"]]
gene_name <- str_remove_all(counts_matrix$GeneName, "\\.*")
# Filter by common rows
common_rows <- Reduce(intersect, list(colnames(counts_matrix), rownames(blocks), names(batches)))
counts_matrix <- select(counts_matrix, common_rows)

blocks <- data.frame(blocks)[common_rows, ] %>% select(contains(c("Mucocutaneous", "Musculoskeletal", "Urticaria", "Myocarditis", "Corticosteroid", "DMARDs", "Anti.IL1", "Anti.IL6")))
batches <- batches[common_rows]

# c(list.map(l_visits, f(i) ~ colnames(i)[-1]), CLINIC = list(rownames(blocks)))
# plot_venn1(temp, color = c("#FED976", "#FD8D3C", "#377EB8"))
```

```{r}
# db_annot <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl", version = 104)
# datasets <- listDatasets(db_annot)
# filter(datasets, str_detect(description, "Human")) %>% pull(version)

# gene_query <- getBM(
#     attributes = c("ensembl_gene_id", "hgnc_symbol"),
#         filters = "ensembl_gene_id",
#         values = gene_name,
#         mart = db_annot
#     )

gene_query <- read_tsv(file = file.path(path, "martquery.tsv")) %>% set_colnames(c("ensembl_gene_id", "hgnc_symbol"))
# which(is.na(gene_query$`Gene name`)) %>% length()
gene_query[duplicated(gene_query$ensembl_gene_id) %>% which(), ] %>%
    pull(ensembl_gene_id) %>%
    paste0("^", ., "$") %>%
    list.map(., f(i) ~ filter(gene_query, str_detect(ensembl_gene_id, i)))

# duplicates <- gene_query[duplicated(gene_query$ensembl_gene_id) %>% which(), 1]
# gene_query <- gene_query[!gene_query$ensembl_gene_id %in% duplicates, ] %>% rbind(data.frame(ensembl_gene_id = c("ENSG00000277796", "ENSG00000277768", "ENSG00000277336", "ENSG00000276085", "ENSG00000230417"), hgnc_symbol = c(rep("CCL3L1/3", 4), "LINC00595/LINC00856")))

counts_matrix <- mutate(counts_matrix, ensembl_gene_id = gene_name) %>%
    left_join(gene_query) %>%
    arrange(hgnc_symbol) %>%
    # select(-ensembl_gene_id) %>%
    mutate(hgnc_symbol = str_replace_all(hgnc_symbol, "^$", "Unkown"))
counts_matrix[is.na(counts_matrix)] <- "Unknown"
counts_matrix <- data.frame(counts_matrix) %>%
    arrange(hgnc_symbol)
gene_hgnc <- pull(counts_matrix, hgnc_symbol) %>%
    snakecase::to_any_case(case = "none", sep_in = NULL, unique_sep = "_")
ensembl_ids <- pull(counts_matrix, ensembl_gene_id)
counts_matrix <- select(counts_matrix, -c(hgnc_symbol)) %>%
    set_colnames(colnames(counts_matrix)[-c(38)] %>% str_remove_all("^X")) %>%
    set_rownames(gene_hgnc)
# use_data(counts_matrix, overwrite = TRUE)
```

```{r, eval = FALSE}
gene_counts <- list.map(
    seq(3),
    f(i) ~ {
        list.map(
            list.files(
                path = file.path(path, "RNASeq", "gene_counts", paste0("Batch", i)),
                full.names = TRUE,
                pattern = "tsv"
            ),
            f(i) ~ {
                read_tsv(i, col_names = FALSE) %>%
                    select(X1, X2) %>%
                    set_colnames(c("id", str_extract(i, "\\d{5}[AB]05PB1")))
            }
        ) %>% Reduce(function(x, y) full_join(x, y, by = "id"), .)
    }
) %>% Reduce(function(x, y) full_join(x, y, by = "id"), .)
# use_data(gene_counts, overwrite = TRUE)
```

```{r, eval = FALSE}
# library(sva)
counts_combat <- as.matrix(counts_matrix) %>%
    set_rownames(gene_name) %>%
    ComBat_seq(batches) %>%
    as.data.frame()
counts_combat_HUGO <- ensembl_to_hugo(ensembl_hgnc, counts_combat)
```

```{r}
# setA <- select(counts_matrix, which(groups == 0) %>% names())
# setB <- select(counts_matrix, which(groups == 1) %>% names())
# comparison <- cbind(setA, setB)
# exprs_threshold <- 1 * NCOL(counts_matrix)
library(DESeq2)
filtered_counts <- counts_matrix[apply(select(counts_matrix, -ensembl_gene_id), 1, sum) > 10, ]
ensembl_ids <- pull(filtered_counts, ensembl_gene_id)
filtered_counts <- select(filtered_counts, -ensembl_gene_id) %>% round()
l_de0 <- list.map(colnames(blocks), f(i) ~ {
    DESeqDataSetFromMatrix(
        countData = filtered_counts,
        colData = data.frame(group = factor(blocks[, i]), batch = factor(batches)),
        design = ~ batch + group
    ) %>% DESeq()
})
# results() %>%
l_de <- list.map(l_de0, f(i) ~ lfcShrink(i, coef = "group_1_vs_0") %>%
    as.data.frame())
```

```{r}
list.map(l_de, f(i, k, j) ~ i %>% mutate(log2fc = log2FoldChange, p = pvalue, log10p = -log(padj, 10), name = rownames(.) %>% str_remove_all("_\\d*") %>% toupper(), Expression = case_when(
    log2FoldChange >= 1 & padj <= 0.05 ~ "Up-regulated",
    log2FoldChange <= -1 & padj <= 0.05 ~ "Down-regulated",
    TRUE ~ "ns"
)) %>% filter(log2FoldChange >= 0.01 | log2FoldChange <= -0.01) %>%
    volcano_plot(get_top(., n = 30), cex = 3, title = str_replace(j, "\\.", "-"), xtitle = expression("log"[2] * "FC"), legend = "none") + xlab("") + ylab("")) %>%
    list(pluck(., 1), pluck(., 2), NULL, pluck(., 3), pluck(., 4)) %>%
    # list(pluck(., 1), NULL, NULL, pluck(., 2)) %>%
    plot_grid(
        plotlist = .,
        nrow = 2,
        ncol = 3,
        align = "hv"
    ) %>%
    save_tiff(file.path(path_img, "volcano_treat_b"), 8000, 4000)
```



```{r, eval = FALSE}
list.map(l_de, f(i) ~ filter(i, !is.na(padj)) %>%
    filter(log2FoldChange >= 1 | log2FoldChange <= -1) %>%
    filter(padj <= 0.05) %>%
    arrange(padj))

de_gene_names <- list.map(l_de, f(i) ~ mutate(i, log2fc = log2FoldChange) %>%
    filter(!is.na(padj)) %>%
    filter(!str_detect(rownames(.), "unknown")) %>%
    get_top(0.5, 1) %>%
    rownames() %>%
    str_remove_all("_\\d") %>%
    unique() %>%
    toupper())

res <- results(l_de0[[4]])
summary(res)
as.data.frame(res) %>%
    arrange(log2FoldChange) %>%
    head()

without_unknown <- res %>%
    as.data.frame() %>%
    filter(!str_detect(rownames(.), "unknown"))
(de_genes <- res %>% as.data.frame() %>% arrange(padj) %>% filter(padj <= 0.05))

de_gene_names <- de_genes %>%
    rownames() %>%
    str_remove_all("_\\d") %>%
    unique() %>%
    toupper()
de_genes_ranked <- without_unknown$log2FoldChange %>%
    set_names(rownames(without_unknown) %>% str_remove_all("_\\d*") %>% toupper()) %>%
    sort(decreasing = TRUE)
# plotMA(res, alpha = 0.05, colSig = "red", ylim = 3 * c(-1, 1))
res %>%
    as.data.frame() %>%
    arrange(desc(log2FoldChange)) %>%
    head()
plotCounts(l_de0[[4]], gene = "HLA-DQA1_4", intgroup = "group", returnData = TRUE) %>%
    mutate(group = factor(group, labels = c("Yes", "No"))) %>%
    ggplot(aes(x = group, y = count, color = group)) +
    geom_point(position = position_jitter(w = 0.1, h = 0)) +
    scale_y_log10(breaks = c(25, 100, 400)) +
    theme_bw() +
    ylab("Count") +
    xlab("Anti-IL6") +
    scale_color_manual(values = get_colors()[c(3, 1)], name = "Anti-IL6") +
    theme(legend.position = "none")
# use_data(l_de_manif, overwrite = TRUE)
```


```{r}
de_genes <- list.map(l_de, f(i) ~ mutate(i, log2fc = log2FoldChange) %>%
    filter(!is.na(padj)) %>%
    get_top(0.5, 0.2, n = 200) %>%
    filter(!str_detect(rownames(.), "Unknown")) %>%
    rownames() %>%
    str_remove_all("_\\d") %>%
    unique())
sapply(de_genes, length)

# de_genes_ranked <- list.map(l_de, f(i) ~ {filter(i, !is.na(padj)) %>% filter(log2FoldChange >= 0.5 | log2FoldChange <= -0.5) %>% filter(pvalue <= 0.2) %>% filter(!str_detect(rownames(.), "Unknown")) -> tmp; tmp$log2FoldChange %>%
#     set_names(rownames(tmp) %>% str_remove_all("_\\d*")) %>%
#     sort(decreasing = TRUE)})

de_genes_ranked <- list.map(l_de, f(i) ~ {
    mutate(i, ensembl_ids = ensembl_ids, log2fc = log2FoldChange) %>%
        filter(!is.na(padj)) %>%
        get_top(0.01, 1) -> tmp
    tmp$log2FoldChange %>%
        set_names(pull(tmp, ensembl_ids)) %>%
        sort(decreasing = TRUE)
})
sapply(de_genes_ranked, length)
```


```{r}
for (x in colnames(blocks)) {
    p <- enrichr(de_genes[[x]], dbs) %>% list.map(f(i, j) ~ plot_enrich(i, n = 15, title = str_replace_all(dbs[j], "_", " ")))
    plot_grid(
        plotlist = p,
        nrow = 2,
        ncol = 3,
        align = "hv"
    ) %>%
        save_tiff(file.path(path_img, "shrinked", paste0("enrichr_", x, "_skrinked")), 8000, 4000)
}
l_enrich <- list.map(de_genes, f(x) ~ enrichr(x, dbs))
p <- list.map(l_enrich, f(i, j, k) ~ plot_enrich(i[[5]], n = 15, title = str_replace_all(k, "\\.", "-")))
plot_grid(
    plotlist = p[c(1, 4)],
    nrow = 1,
    ncol = 2,
    align = "hv"
)
```


```{r}
# ClusterProfiler
organism <- "org.Hs.eg.db"
library(organism, character.only = TRUE)
gse <- list.map(de_genes_ranked, f(i) ~ gseGO(i, ont = "BP", OrgDb = get(organism), keyType = "ENSEMBL"))
# dotplot(gse, showCategory = 10)

p <- list.map(gse, f(i) ~ data.frame(i)) %>%
    keep(function(i) nrow(i) > 0) %>%
    list.map(f(i, j, k) ~ data.frame(i) %>%
        mutate(Adjusted.P.value = p.adjust, Term = str_to_title(Description), Count = setSize, Overlap = core_enrichment) %>%
        plot_enrich(10, gsea = TRUE, title = k)) %>%
    # list(pluck(., 1), pluck(., 2), NULL, pluck(., 3), pluck(., 4)) %>%
    plot_grid(
        plotlist = .,
        nrow = 2,
        ncol = 3,
        align = "hv"
    ) %>%
    save_tiff(file.path(path_img, "gsea_treat2"), 8000, 4000)
```


```{r, eval = FALSE}
kegg_genes <- list.map(de_genes_ranked, f(i) ~ {
    bitr(names(i), fromType = "ENSEMBL", toType = c("ENTREZID"), OrgDb = get(organism)) %>% left_join(data.frame(ENSEMBL = names(i), log2FoldChange = i)) -> tmp
    tmp$log2FoldChange %>%
        set_names(pull(tmp, ENTREZID)) %>%
        sort(decreasing = TRUE)
})

tmp <- list.map(kegg_genes, f(i) ~ gseKEGG(
    geneList = i,
    organism = "hsa",
    keyType = "ncbi-geneid"
))
```
