---
title: "QC"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{QC}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(multiAnalysis)
set.seed(1)

plot_dimred <- function(
  coord,
  axis,
  eig = NULL,
  geom = "point",
  axis_text = FALSE,
  legend = "Batch",
  colour = get_colors(), 
  force = 0.2,
  alpha = 1,
  ...) {
    
  coord <- as.data.frame(coord) %>% set_colnames(c("x", "y", "var"))
  if (!is.null(eig)) {
      axis <- paste0(axis, " (", paste(round(eig[seq(2)], 1), "%)"))
  }
  p <- ggplot(coord, aes(x = x, y = y, color = var)) +
    geom_hline(yintercept = 0, size = .5, color = "gray70") +
    geom_vline(xintercept = 0, size = .5, color = "gray70") +
    labs(x = axis[1], y = axis[2], color = legend) +
    theme_minimal() +
    theme(
        axis.title = element_text(size = 15, face = "bold.italic", color = "gray50"),
        legend.title = element_text(size = 15, face = "bold.italic", color = "gray50"),
        legend.text = element_text(size = 13, color = "gray50")
    )
  if (pull(coord, "var") %>% is.numeric()) {
    p <- p + scale_color_gradientn(colors = c("darkblue", "#A6CEE3", "#FB9A99", "darkred"))
  } else {
    p <- p + 
      scale_color_manual(
        values = colour, 
        na.value = brewer.pal(n = 8, name = "Set2")[6]
      ) +
      guides(color = guide_legend(override.aes = list(shape = 15, size = 4)))
  }
    
  if (axis_text) {
    p <- p + theme(axis.text = element_text(size = 13, color = "gray50"))
  } else {
    p <- p + theme(axis.text = element_blank())
  }
  if (geom == "point") {
    p + geom_point(alpha = alpha)
  } else {
    p + geom_text_repel(aes(label = rownames(coord)), force = force, max.iter = 500, ..., alpha = alpha)
  }
}

trans_coord <- function(coord, add = NULL) {
  res <- as.data.frame(coord) %>% 
  set_colnames(axis)
  if (!is.null(add))
    res %>% mutate(batch = add)
  else
    res
}

ncomp <- 2
axis <- paste0("Dim. ", seq(ncomp))
```

```{r}
path <- golem::get_golem_wd()
cwd <- file.path(path, "inst", "extdata")
raw_counts <- read_tsv(file.path(cwd, "gene_counts.tsv")) %>% 
  column_to_rownames("gene_id")
batch <- read_tsv(file.path(cwd, "batch_rna.tsv")) %>% 
  mutate(batch = as.factor(batch))
batch <- data.frame(Sample = colnames(raw_counts)) %>% 
  full_join(batch, by = "Sample") %>% 
  column_to_rownames("Sample") %>% 
  pull(batch)
age0 <- interval(
    (complete_date(clinic$C_2648_3887) %>% dmy()),
    (complete_date(clinic$C_2643_3802) %>% dmy())
) / years(1)
clinic <- clinic %>% #read_tsv(file.path(cwd, "clinic.tsv")) %>% 
  select(c("C_2643_3796", "C_2649_3888", "C_2649_3895", "C_2643_3803", "C_2649_3890")) %>%
  set_colnames(c("Sample", "Gender", "Ethnicity", "Age", "BMI")) %>%
  mutate(Sample = as.numeric(Sample) %>% as.character()) %>%
  mutate(`Disease duration` = age0)
```
# Data
```{r data}
combat_counts <- as.matrix(raw_counts) %>%
    ComBat_seq(batch) %>%
    as.data.frame()
norm_rna0 <- round(raw_counts) %>% as.matrix() %>% vst()
colnames(norm_rna0) <- colnames(norm_rna0) %>% str_remove_all("05PB1")
norm_rna <- select(facs, !matches("(.*median.*)|(.*iqr.*)"))
batch <- blocks[[1]]$gender # pull(batch_facs, 1)
norm_rna1 <- apply(norm_rna, 2, function(x) {x[is.na(x)] <- median(x, na.rm = TRUE); x})
norm_rna <- round(combat_counts) %>% as.matrix() %>% vst()
colnames(norm_rna) <- colnames(norm_rna) %>% str_remove_all("05PB1")
# norm_rna0 <- apply(facs, 2, function(x) {x[is.na(x)] <- median(x, na.rm = TRUE); x})
norm_rna %>% as.data.frame() %>% 
  rownames_to_column("gene_id") %>% 
  write_tsv(file.path(path, "gene_nobatch_normalized.tsv"))

norm_rna0 <- counts(l_de0[[1]], normalized=TRUE) %>%
    round() %>%
    as.matrix()
```

# UMAP
```{r umap}
res <- umap(t(norm_rna0))
coord <- trans_coord(res$layout, add = batch)
plot_dimred(coord, axis)
metadata <- rownames_to_column(coord, "ID") %>% 
  mutate(Sample = str_remove_all(ID, "[AB].?")) %>%
  left_join(clinic, by = "Sample") %>%
  mutate(Group = blocks[[1]]$group)

x <- 1
p <- list.map(
  c("Gender", "Ethnicity"),
  f(i, j) ~ {
    select(metadata, c(axis[x], i)) %>% 
    filter(!is.na(!!sym(i))) %>% 
    group_by(!!sym(i)) %>%
    group_split() %>%
    as.list() %>%
    list.map(f(i) ~ pull(i, 1)) %>%
    list_cbind0() %>%
    round() %>%
    set_colnames(unique(pull(metadata, i)) %>% na.omit() %>% sort()) %>%
    plot_violin(
        method  = "wilcox",
        width_text = 5,
        width_title = 20,
        colour = brewer.pal(10, "Paired")[3:4 + 2 * j],
        color_title = brewer.pal(10, "Paired")[4 + 2 * j],
        stats = TRUE,
        title = i
    ) +
      theme(plot.subtitle = element_text(hjust = 0.5, size = 17))
  }
)

mod <- lm(`Dim. 1` ~ Gender * Group, data = metadata)
summary(mod)

p2 <- list.map(
  c("Gender", "Ethnicity"),
  f(i, j) ~ {
    lapply(
      unique(pull(metadata, i)) %>% na.omit(),
      function(var) {
        select(metadata, c(axis[x], i, Group)) %>% 
        filter(!is.na(!!sym(i))) %>%
        filter(!!sym(i) == var) %>%
        group_by(Group) %>%
        group_split() %>%
        as.list() %>%
        list.map(f(i) ~ pull(i, 1)) %>%
        list_cbind0() %>%
        round() %>%
        set_colnames(c("HV", "SD")) %>%
        plot_violin(
            method  = "wilcox",
            width_text = 5,
            width_title = 20,
            colour = get_colors()[c(5, 3)],
            color_title = "black",
            stats = TRUE,
            title = var
        ) +
          theme(plot.subtitle = element_text(hjust = 0.5, size = 17))
      }
    ) %>%
      plot_grid(
        plotlist = .,
        ncol = 2,
        align = "hv"
      )
  }
)
list.map(
  c("Age", "BMI"),
  f(i, j) ~ select(metadata, c(axis[x], i)) %>% plot_cor2(color = get_colors()[j + 1], title = i)
) %>% c(p, .) %>%
plot_grid(
  plotlist = .,
  nrow = 2,
  ncol = 2
)

list.map(
  c("Age", "Disease duration", "BMI"),
  f(i, j) ~ {
    list.map(
      unique(pull(metadata, "Group")),
      f(x) ~ {
    filter(metadata, Group == x) %>%
      select(c(axis[x], i)) %>% 
      plot_cor2(color = get_colors()[j + 1], title = x)
      }
    ) %>%
      plot_grid(
        plotlist = .,
        ncol = 2,
        align = "hv"
      )
  }
)

plot_grid(
  plotlist = .,
  nrow = 2,
  ncol = 2
)

list.map(
  c("Gender", "Ethnicity", "Age", "BMI"),
  f(var) ~ select(c(2:3, var)) %>% plot_dimred(axis, legend = var)
) %>%
  plot_grid(
  plotlist = .,
  nrow = 2,
  ncol = 2,
  align = "hv"
)

select(metadata, c(2:3, Group)) %>% mutate(Group = ifelse(Group == 0, "HV", "SD")) %>% plot_dimred(axis, eig = eig, legend = "Group", colour = get_colors()[c(5, 3)]) + theme(legend.position = "none")
```

# PCA
```{r pca}
res_pca <- PCA(norm_rna1, scale.unit = FALSE, ncp = ncomp, graph = FALSE)
coord <- trans_coord(res_pca$ind$coord, add = batch)
res_pca$eig[, "percentage of variance"] %>%
  plot_dimred(coord, axis, eig = .)
outs <- lapply(seq(ncomp), function(x) get_outliers(res$layout[, x], method = "iqr", replace = FALSE))
lapply(seq(ncomp), function(x) get_outliers(res_pca$ind$coord[, x], method = "mad", replace = FALSE, c = 6))
```

# RGCCA
```{r}
res_rgcca <- rgcca(norm_rna, ncomp = 5, method = "pca", scale = FALSE, scale_block = FALSE)
coord <- trans_coord(res_rgcca$Y[[1]][, seq(ncomp)], add = batch)
(res_rgcca$AVE$AVE_outer * 100) %>%
  plot_dimred(coord, axis, eig = .)
(coord[, 1] - min(coord[, 1])) %>% cbind(pull(batch, 1)) %>% chisq_test(workspace = 1e8)
rgcca_weights <- res_rgcca$a[[1]]
dim <- 1
title <- (res_rgcca$AVE$AVE_outer * 100) %>% 
  round(0) %>%
  paste0("%") %>%
  .[dim]
# c("#99000D", "gray")
abs(rgcca_weights[, dim] * 100) %>% 
  plot_bar(
    n_max = 15,
    cex = 0.7,
    colour =  c("#99000D", "gray"), # ifelse(rgcca_weights[, dim] < 0, "darkred", "forestgreen"),
    width_text = 40,
    title = paste0("Dim. ", dim, ": ", title)
)
```

# MDS
```{r mds}
hc_metric <- "spearman"
norm_rna2 <- t(norm_rna0) %>% remove_constant() %>% scale()
res_dist <- norm_rna2 %>% get_dist(stand = FALSE, method = hc_metric)

mds <- cmdscale(res_dist, k = ncomp, eig = TRUE, x.ret = TRUE)
# mds <- cmdscale(1 - rf$proximity, k = ncomp, eig = TRUE)
mds$points[, 1] <- mds$points[, 1] * -1
coord <- trans_coord(mds$points, add = batch)
eig <- (mds$eig / sum(mds$eig) * 100) #[mds$eig > 0]
  plot_dimred(coord, axis, eig = eig, colour = get_colors()[c(3, 5)]) + 
  theme(legend.position = "none")
lapply(
  unique(batch), 
  function(x) {
    filter(coord, batch == x) %>% arrange(`Dim. 1`)
    }
  )
```

# SOM
```{r som}
som_grid <- somgrid(
    xdim = 3,
    ydim = 3,
    toroidal = TRUE,
    topo = "hexagonal"
)
res_som <- som(
    facs %>% as.matrix(),
    grid = som_grid,
    rlen = 10000,
    normalizeDataLayers = FALSE,
    maxNA.fraction = 101
)

col_grp <- function(x = som_clusters, a = 1, color = get_colors()) {
    x <- as.factor(x)
    levels(x) <- color[seq(levels(x))]
    return(as.vector(x))
}

plot(
    res_som,
    type = "mapping",
    cex = 0.8,
    # labels = colnames(facs),
    # cex = 3
    # labels = rep(".", ncol(norm_rna))
    col = col_grp(x = batch),
    bg = "white",
    shape = "straight",
    border = "gray50"
)
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")
```

# HAC
```{r ward}
res_clus <- hclust(res_dist, method = "ward.D2")
df <- as.matrix(res_dist)
annot <- data.frame(Batch = batch)
rownames(annot) <- rownames(facs)
row_col <- get_colors()[c(1, 3:5, 2)] %>% set_names(unique(batch)) %>% list(Batch = .)
pheatmap(
    df,
    color = colorRampPalette(colors_ind)(100),
    angle_col = 315,
    na_col = "white",
    annotation_col = annot,
    border_color = NA,
    annotation_colors = row_col,
    cluster_rows = res_clus,
    cluster_cols = res_clus,
    cutree_rows = k,
    cutree_cols = k,
    fontsize = 12,
    show_rownames = FALSE,
    show_colnames = FALSE
)
```

# NHC
```{r pam}
MAX_CLUSTERS <- 10
res_nhc <- getClassif(1, MAX_CLUSTERS, t(norm_rna), res_dist)
cls <- getClusterPerPart(MAX_CLUSTERS, res_nhc)
sil <- getSilhouette(cls[[k-1]], t(norm_rna))
heatMap(t(norm_rna), res_dist, sil, NULL, NULL)
```

```{r}
data("counts_combatseq")
data("gene_query")
counts_matrix0 <- rename(counts_combatseq, ensembl_gene_id = gene_id) %>%
    left_join(gene_query) %>%
    arrange(hgnc_symbol) %>%
    data.frame() %>%
    filter(!str_detect(hgnc_symbol, "^$"))
gene_hgnc <- pull(counts_matrix0, hgnc_symbol) %>%
    snakecase::to_any_case(case = "none", sep_in = NULL, unique_sep = "_")
facs <- select(counts_matrix0, -c(ensembl_gene_id, hgnc_symbol)) %>% 
    set_colnames(colnames(.) %>% str_remove_all("^X")) %>%
    round() %>%
    as.matrix() %>% 
    vst() %>%
    t() %>% 
    as.data.frame() %>%
    set_colnames(gene_hgnc)

dis <- "(Adult)|(Systemic)"
clinic1 <- clinic %>%
  filter(!str_detect(C_2643_3798, "(suspi)|(angiosarcoma)|(Crohn)")) %>%
  filter(str_detect(C_2643_3798, paste0(dis, "|(Negative)")))

temp <- inner_join(
    as.data.frame(facs) %>% filter(str_detect(rownames(.), "A")) %>% mutate(ID = rownames(.) %>% str_remove_all("[AB](\\d{2}PB\\d)?") %>% as.numeric()),
    mutate(clinic1, ID = as.numeric(C_2643_3796))
)
res_scaled <- temp %>% column_to_rownames("ID") %>% select(top_genes)

get_top0(l_de2[[1]], n = 100) %>% rownames() -> top_genes
control <- filter(blocks1[[1]], group == 0) %>% rownames()
sd <- filter(blocks1[[1]], group == 1) %>% rownames()
rbind(res_scaled[sd, ], res_scaled[control, ]) %>% as.data.frame() %>% scale0("minmax") %>% plot_heatmap(cex = 0.7, colour = c("blue", "gray", "#cd5b45"))
```

# FACS
```{r}
data("clinic")
# data("facs")
# lapply(
#     c(                           
#         "Live Cells", 
#         "B Cells", 
#         "NK Cells",
#         "T Cells",
#         "Monocytes",
#         "Dendritic Cells",
#         "CD4\\+ T Cells",
#         "CD8\\+ T Cells"
#     ),
#     function(i)
#         colnames(facs) %>%
#         str_extract_all(paste0(".*in ", i)) %>%
#         unlist() %>%
#         discard(function(x) str_detect(x, "(^No )|(^Double Negative)|(median)|(iqr)")) %>% 
#         sort()
# ) %>% unlist() -> cells0
facs1 <- facs %>% filter(str_detect(rownames(.), "A")) %>%
  select(cells0)

colnames(facs1) <- colnames(facs1) %>% str_replace_all("(GROalpha)", "\\1/CXCL1") %>% str_replace_all("al((ph)|(f))a", "\u03b1") %>% str_replace_all("beta", "\u03b2") %>% str_replace_all("gamma", "\u03b3") %>% str_replace_all("lambda", "\u03bb") %>% str_replace_all("_", "/") %>% str_replace_all("(Fractalkine)", "\\1/CX3CL1") %>% str_replace_all("(MDC)", "\\1/CCL22") %>% str_replace_all("(IP-10)", "CXCL10/\\1") %>% str_replace_all("(MCP-1)", "\\1/CCL2") %>% str_replace_all("(IL-28b)-(IFNλ3)", "\\2/\\1") %>% str_replace_all("(IL-37)-(IL-1F7)", "\\1/\\2") %>% str_replace_all("MIG/CXCL9", "CXCL9/MIG")
facs1 <- facs1 %>% select(sort(colnames(.)))


# facs1 <- counts_matrix %>% select(matches("A\\.")) %>% t() %>% as.data.frame() %>% select(sort(colnames(.))) %>% set_rownames(rownames(.) %>% str_remove_all("A\\."))
cells0 <- de_genes0[[1]]
facs1 <- counts_combatseq %>% filter(str_detect(rownames(.), "A")) %>% select(cells0)
```


```{r}
dis <- "(Adult)|(Systemic)"
pos <- "SD"
col_pos <- "#4DAF4A"
col_neg <- "black"
# dis <- "(Chronic)"
# pos <- "CRO"
# col_pos <- "#FFD92F"
neg <- "SAID"
clinic1 <- clinic %>%
  filter(!str_detect(C_2643_3798, "(suspi)|(angiosarcoma)|(Crohn)")) %>%
  # filter(str_detect(C_2643_3798, paste0(dis, "|(Negative)")))
  filter(!str_detect(C_2643_3798, "Negative"))
facs0 <- inner_join(
  as.data.frame(facs1) %>% mutate(ID = rownames(.) %>% str_remove_all("A") %>% as.numeric()), 
  clinic1 %>% mutate(ID = as.numeric(C_2643_3796))
) %>% 
  column_to_rownames("ID")
disease1 <- facs0$C_2643_3798 %>% 
        # str_replace_all("(Adult.*", "AOSD") %>%
        # str_replace_all("Systemic.*", "SOJIA") %>%
        str_replace_all("(Systemic.*)|(Adult.*)", "SD") %>%
        str_replace_all("Chronic.*", "CRO") %>%
        str_replace_all("Inflammation.*", "IUO") %>%
        str_replace_all("Pediatric.*", "PIMS") %>% 
        str_replace_all("Recurrent (Pericarditis)", "\\1") %>%
        str_replace_all("(Negative control)", "HV") %>%
        str_remove_all(" \\(.*")
Y <- as.factor(disease1) %>%  set_names(rownames(facs0))
disease0 <- str_replace_all(disease1, "(.*Takayasu.*)|(.*Behçet.*)|(.*Kawasaki.*)", GimmeMyPlot:::palette_discrete()[1]) %>%
        str_replace_all("(.*Pyoderma gangrenosum.*)|(.*Sweet syndrome.*)", GimmeMyPlot:::palette_discrete()[2]) %>%
        str_replace_all("(AOSD)|(SOJIA)|(Still's Disease)|(Systemic.*)|(Adult.*)|(SD)", GimmeMyPlot:::palette_discrete()[3]) %>% 
        str_replace_all("(FMF)|(TRAPS)|(CAPS)|(HIDS)", GimmeMyPlot:::palette_discrete()[4]) %>%
        str_replace_all("(IUO)|(Inflammation.*)", GimmeMyPlot:::palette_discrete()[5]) %>%
        str_replace_all("(Negative control)|(HV)", "black") %>%
        str_replace_all("Pericarditis", GimmeMyPlot:::palette_discrete()[6]) %>%
        str_replace_all("Schnitzler", GimmeMyPlot:::palette_discrete()[7]) %>%
        str_replace_all("(CRO)|(Chronic.*)", GimmeMyPlot:::palette_discrete()[8]) %>%
        str_replace_all("(PIMS)|(Pediatric.*)", GimmeMyPlot:::palette_discrete()[9]) %>%
  set_names(rownames(facs0))
disease <- ifelse(str_detect(facs0$C_2643_3798, dis), pos, neg) %>% as.factor() -> Y
row_col <- c(col_pos, col_neg) %>% set_names(c(pos, neg)) %>% .[sort(c(pos, neg))]
row_annotation <- data.frame(Disease = disease)
names_levels <- levels(disease)
# cells0 <- colnames(facs1)
# cells0 <- unlist(de_genes0) %>% unname()
facs0 <- select(facs0, cells0) %>% remove_constant() -> fact_tot0
# res_scaled_na <- scale0(facs0, "minmax")
# fact_tot0 <- apply(facs0, 2, function(x) {x[is.na(x)] <- median(x, na.rm = TRUE); x})
# res_scaled <- scale0(fact_tot0)
```

```{r}
cols <- brewer.pal(n = 11, name = "RdBu")
cols <- colorRampPalette(cols)(8)
cols[3:6] <- "white"

c("FAM20A", "RNASE2", "SLC1A3", "KREMEN1", "METTL7B", "ADM", "E2F2", "MMP8", "MKI67", "KIF23", "IQGAP3", "GRB10", "CLSPN", "CD177", "KLRB1", "MYBL1", "SEZ6L", "RAB13") %>% sort() -> vars1

c("HLA-DR+ CD38high CD8+ T Cells in CD8+ T Cells","HLA-DR+ CD38high CD4+ T Cells in CD4+ T Cells", "CD38+ CD8+ T Cells in CD8+ T Cells", "CD38+ CD4+ T Cells in CD4+ T Cells", "HLA-DR+ CD8+ T Cells in CD8+ T Cells", "HLA-DR+ CD4+ T Cells in CD4+ T Cells", "CD86+ CD8+ T Cells in CD8+ T Cells", "BAFF-Rhigh B Cells in B Cells", "NK Cells in Live Cells", "HLA-DR+ NK Cells in NK Cells", "CD38+ NK Cells in NK Cells", "CD38+ Monocytes in Monocytes") -> vars2
c("IL-1RA", "IL-6", "IL-10", "IL-18", "CXCL9/MIG", "CXCL10/IP-10", "G-CSF") -> vars3
c("IL-1β", "IL-1RA", "Free IL-18", "Total IL-18", "IL-18BP" ) -> vars4
c("IL-1RA", "IL-18") -> vars5

# list.map(c("CLSPN", "E2F2", "KIF23", "MKI67"),
#          f(i) ~{
# l_blocks <- list(select(blocks[[3]], vars3 %>% .[str_detect(., "(IL-18)|(CXCL)")]),
l_blocks <- list(select(blocks[[1]], vars1),
# l_blocks <- list(select(blocks[[2]], vars2 %>% .[str_detect(., "CD8")]),
                 # select(blocks[[1]], i),
# l_blocks <- list(select(luminex_geneva, vars4), select(blocks[[3]], vars5),
                 clinic0  %>% filter(Group == "SD") %>% set_rownames(paste0(rownames(.), "A")))
l_rownames <- list.map(l_blocks, f(x) ~rownames(x) %>% .[str_detect(., "A")] %>% str_remove_all("A.*")) %>% Reduce(intersect, .)
x <- l_blocks[[1]][paste0(l_rownames, "A"), , drop = FALSE]  %>% set_colnames(colnames(.) %>% str_remove_all(" in CD8\\+ T Cells"))
y <- l_blocks[[2]][paste0(l_rownames, "A"), , drop = FALSE]

clinic0 <- pull(clinic1, C_2643_3798) %>% str_replace_all("((Adult)|(Systemic)).*", "SD") %>%
    str_replace_all(".*control.*", "HV") %>%
    str_replace_all("^((?!(HV)|(SD)).)*$", "SAID") %>%
    data.frame(Group = .) %>%
    set_rownames(pull(clinic1, C_2643_3796) %>% paste0("A"))
res_scaled <- x %>% select("CD177", "CDC45", "CDCA5", "DTL", "E2F8", "IL1R2", "MCM10", "MKI67", "PKMYT1", "PLIN4", "SLC51A", "ZDHHC19")
res_scaled_na <- scale0(res_scaled, "minmax")
split(rownames(y), factor(y[, 1])) %>% lapply(function(i) res_scaled_na[i, ]) %>% Reduce(rbind, .) %>% plot_heatmap(cex= 0.7, colour = colorRampPalette(colors_ind)(100)) + theme(legend.position = "none") + geom_vline(xintercept = c(68, 265+68), lwd = 2, lty = 2, color = "black")

GimmeMyPlot:::plot_cor(
  x = x,
  y = y,
  xlab = "pg\\ml (log10)",
  legend = "Cytokines",
  # xlab = "%CD8+ T Cells",
  # legend = "Cell population",
  color = get_colors()[c(seq(3), 5)]
)
# }) %>% plot_grid(plotlist = ., ncol = 2, nrow = 2, align = "hv")

res <- GimmeMyPlot:::mcor_test(
    x,
    x,
    TRUE,
    TRUE,
    method = "spearman",
    method_adjust = "BH"
) %>% suppressWarnings()
mat <- res$estimate
p_mat = res$p.value

val <- abs(as.vector(mat))
val <- abs(as.vector(mat[upper.tri(mat)]))
cols2 <- ifelse(val >= 0.75, "white", ifelse(val >= 0.5, "black",  alpha("white", 0)))

# plot_mcor(x = x, y = y, addCoef.col = cols2, colour = cols)
plot_mcor(x = x, addCoef.col = cols2, colour = cols, number.cex = 0.75, cex = 0.75)
abs(res$estimate) %>% apply(1, median) %>% multiply_by(100) %>% plot_bar(label_x = "value")
#addCoef.col = "black
# number.cex
```

```{r}
power <- c(c(1:10), seq(from = 12, to = 50, by = 2))

sft <- pickSoftThreshold(
  x,
  powerVector = power,
  networkType = "unsigned",
  verbose = 5
)

sft.data <- sft$fitIndices

# visualization to pick power

a1 <- ggplot(sft.data, aes(Power, SFT.R.sq, label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  geom_hline(
    yintercept = 0.8,
    color = 'red',
    lwd = 1.25,
    lty = 2
  ) +
  labs(x = 'Power', y = 'Scale free topology model fit, signed R^2') +
  theme_classic()


a2 <- ggplot(sft.data, aes(Power, mean.k., label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  labs(x = 'Power', y = 'Mean Connectivity') +
  theme_classic()

plot_grid(a1, a2, nrow = 2)

soft_power <- 18
temp_cor <- cor
cor <- WGCNA::cor

# memory estimate w.r.t blocksize
bwnet <- blockwiseModules(
  x,
  maxBlockSize = 14000,
  # TOMType = "signed",
  # corType = "pearson",
  power = soft_power,
  # mergeCutHeight = 0.25,
  numericLabels = TRUE,
  randomSeed = 1234,
  blockSizePenaltyPower = 10
  verbose = 3
)

cor <- temp_cor
module_eigengenes <- bwnet$MEs

# Print out a preview
head(module_eigengenes)

# get number of genes for each module
table(bwnet$colors)
bwnet$colors %>% split(as.factor(.))

plotDendroAndColors(
  bwnet$dendrograms[[1]],
  cbind(bwnet$unmergedColors, bwnet$colors),
  c("unmerged", "merged"),
  dendroLabels = FALSE,
  addGuide = TRUE,
  hang = 0.03,
  guideHang = 0.05
)

```

