---
title: "RGCCA"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RGCCA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Setup
```{r setup}
set.seed(1)
library(multiAnalysis)
library("RGCCA")
# set_analysis(block_name = "rna_clinic_still2", type = "list", to_remove = c("1007", "1014", "9001"))
# load_all(path = file.path(cwd, "inst", "RGCCA"))
data("luminex") 
data("facs")
data("gene_query")
data("counts_combatseq")
ncomp <- 2
n <- 1
```

# Data preparation
```{r data}
# FACS
lapply(
    c(
        "Live Cells",
        "B Cells",
        "NK Cells",
        "T Cells",
        "Monocytes",
        "Dendritic Cells",
        "CD4\\+ T Cells",
        "CD8\\+ T Cells"
    ),
    function(i)
        colnames(facs) %>%
        str_extract_all(paste0(".*in ", i)) %>%
        unlist() %>%
        purrr:::discard(function(x) str_detect(x, "(^No )|(^Double Negative)|(median)|(iqr)")) %>%
        sort()
) %>% unlist() -> cells
facs <- select(facs, cells) %>% apply(2, function(x) {x[is.na(x)] <- median(x, na.rm = TRUE); x}) %>% as.data.frame()

# Luminex
luminex <- apply(luminex, 2, function(x) {x[is.na(x)] <- median(x, na.rm = TRUE); x}) %>% as.data.frame()
colnames(luminex) <- colnames(luminex) %>% str_replace_all("(GROalpha)", "\\1/CXCL1") %>% str_replace_all("al((ph)|(f))a", "\u03b1") %>% str_replace_all("beta", "\u03b2") %>% str_replace_all("gamma", "\u03b3") %>% str_replace_all("lambda", "\u03bb") %>% str_replace_all("_", "/") %>% str_replace_all("(Fractalkine)", "\\1/CX3CL1") %>% str_replace_all("(MDC)", "\\1/CCL22") %>% str_replace_all("(IP-10)", "CXCL10/\\1") %>% str_replace_all("(MCP-1)", "\\1/CCL2") %>% str_replace_all("(IL-28b)-(IFNλ3)", "\\2/\\1") %>% str_replace_all("(IL-37)-(IL-1F7)", "\\1/\\2") %>% str_replace_all("MIG/CXCL9", "CXCL9/MIG")
luminex <- luminex %>% apply(2, function(x) {x[is.na(x)] <- median(x, na.rm = TRUE); x}) %>% as.data.frame()

# RNA
counts_combatseq <- rename(counts_combatseq, ensembl_gene_id = gene_id) %>%
    left_join(gene_query) %>%
    arrange(hgnc_symbol) %>%
    data.frame() %>%
    filter(!str_detect(hgnc_symbol, "^$"))
gene_hgnc <- pull(counts_combatseq, hgnc_symbol) %>%
    snakecase::to_any_case(case = "none", sep_in = NULL, unique_sep = "_")
counts_combatseq <- select(counts_combatseq, -c(ensembl_gene_id, hgnc_symbol)) %>% 
    set_colnames(colnames(.) %>% str_remove_all("^X")) %>%
    round() %>%
    as.matrix() %>% 
    vst() %>%
    t() %>% 
    as.data.frame() %>%
    set_colnames(gene_hgnc) %>%
    set_rownames(rownames(.) %>% str_remove_all("\\d{2}PB\\d"))

# gene_hgnc %>% .[str_detect(., "SAA")]  %>% select(counts_combatseq, .) %>% list.map(f(i, j, k) ~plot_violin(i, stats = FALSE, display_log = TRUE, title = k)) %>% plot_grid(plotlist = ., ncol = 5, aligne = "hv")
```

```{r data}
# Clinic
clinic1 <- clinic %>%
  filter(!str_detect(C_2643_3798, "(suspi)|(angiosarcoma)|(Crohn)")) #%>%
  # filter(str_detect(C_2643_3798, paste0(dis, "|(Negative)")))
  # filter(!str_detect(C_2643_3798, "Negative"))

# Blocks
blocks <- list(RNA = counts_combatseq, Cell = facs, Cytokine = luminex)

l_rownames <- list.map(blocks, f(x) ~rownames(x) %>% .[str_detect(., "A")] %>% str_remove_all("A.*"))
l_rownames0 <- list.map(l_rownames, f(x) ~ x[as.numeric(x) %in% as.numeric(clinic1$C_2643_3796)])
# plot_venn(l_rownames, cex = 1.5, label = FALSE)
# plot_venn(l_rownames0, cex = 1.5, label = FALSE)

common_rows <- Reduce(intersect, l_rownames0)

clinic0 <- filter(clinic1, C_2643_3796 %in% common_rows) %>% 
  pull(C_2643_3798)
# clinic0 <- ifelse(str_detect(clinic0, dis), pos, neg) %>%
clinic0 <- str_replace_all(clinic0, "((Adult)|(Systemic)).*", "SD") %>%
    str_replace_all(".*control.*", "HV") %>%
    str_replace_all("^((?!(HV)|(SD)).)*$", "SAID") %>%
    # str_replace_all("^((?!SD).)*$", "SAID+HV") %>%
    as.factor() %>%
    data.frame(Group = .) %>%
    set_rownames(common_rows)
  
blocks0 <- list.map(blocks, f(x) ~ {
  x %>%
    filter(str_detect(rownames(.), "A")) %>% 
    set_rownames(rownames(.) %>% str_remove_all("A")) %>%
    filter(rownames(.) %in% common_rows)
  }
) %>% prepend(list(Group = clinic0))

# blocks0[[2]] <- rename(blocks0[[2]], `EGF ` = EGF)
data("deg_common")
blocks0[[2]] <- blocks0[[2]] %>% select(deg_common) # select(c(de_genes0[[1]], "MYBL1", "KLRB1", "SEZ6L", "RAB13"))

blocks0[[n]] <- as.matrix(as.factor(blocks0[[n]][, 1])) %>% set_rownames(rownames(blocks0[[2]])) %>% set_colnames("Group")
n <- 1
```

```{r, eval = FALSE}
data("luminex_geneva")

```

# Model
```{r model}
res <- rgcca(blocks0[c(1, 3:4)], ncomp = ncomp, response = n)
res0 <- rgcca(blocks0[c(1, 3:4)], ncomp = ncomp, superblock = TRUE) #, sparsity = c(1, 0.1)) # tau = "optimal"
# res1 <- rgcca(blocks0[c(1, 3:4, 2)], ncomp = ncomp, superblock = TRUE, sparsity = c(rep(1, 3), 0.2, 0.1))
# res1 <- rgcca(blocks0[c(1, 3:4, 2)], ncomp = ncomp, superblock = TRUE, sparsity = c(1, rep(1, 2), 0.1, 0.08))
res1 <- rgcca(c(Group = list(disj), blocks0[c(2:4)]), ncomp = c(1, rep(2, 3)), superblock = TRUE, sparsity = c(1, 0.1, rep(1, 2), 0.08))
res2 <- rgcca(blocks0[c(1, 3:4, 2)], ncomp = ncomp, response = 1, sparsity = c(rep(1, 3), 0.2))
res3 <- rgcca(blocks0[c(1:2)], ncomp = ncomp, superblock = TRUE, sparsity = c(1, 0.1))
res4 <- rgcca(blocks0[c(1:2)], ncomp = ncomp, response = n, sparsity = c(1, 0.4))
res5 <- rgcca(blocks0[c(2:2)], ncomp = ncomp,  sparsity = rep(0.4, 2))

sapply(ncol(res$a[[2]]), function(i) res$a[[2]][, i] != 0) %>%
    which() %>%
    length()

# Y <- res$Y[[1]][, 1]
```

# Variable
```{r var}
plot_ave(res, cex = 1.8, title = "")
RGCCA::plot_network2(res2, colors = c("gray", "gray"))

plot_var_2D(
    res,
    cex_main = 30,
    cex_lab = 20,
    no_overlap = TRUE,
    i_block = n
)
plot_var_2D(
    res,
    i_block = 1,
    cex_main = 30,
    cex_lab = 20,
    no_overlap = TRUE,
    cex = 1.5,
    n_mark = 10,
    colors = get_colors()[1]
)
plot_var_2D(
    res,
    i_block = 2,
    cex_main = 30,
    cex_lab = 20,
    no_overlap = TRUE
)

plot_var_2D(
    res0,
    i_block = 4,
    cex_lab = 25,
    no_overlap = TRUE,
    cex = 1.5,
    n_mark = 10,
    colors = get_colors()[c(4, 1:3)],
    force = 20,
    title = ""
)

plot_var_2D(
    res1,
    i_block = 5,
    cex_main = 30,
    cex_lab = 30,
    no_overlap = TRUE,
    cex = 2,
    n_mark = 30,
    colors = get_colors()[c(5, 2:3, 1)],
    force = 50,
    title = ""
)

plot_var_1D(
    res1,
    i_block = 5,
    cex_main = 30,
    cex = 2.5,
    n_mark = 20,
    colors = get_colors()[c(5, 2:3, 1)],
    title = ""
)
```

# Stats
```{r stats}
table_occ <- function(x, i, y) {
    sapply(
        y,
        function(j) {
            nrow(
                filter(
                    x,
                    str_detect(
                        as.data.frame(x[, i])[, 1], replace_parenthesis(j)
                    )
                ) %>%
                    select(all_of(i))
            )
        }
    )
}

replace_parenthesis <- function(x) {
    str_replace_all(x, "\\(", "\\\\(") %>%
        str_replace_all("\\)", "\\\\)")
}

clinic_intersect$disease <- as.character(clinic_intersect$disease)

tab_diseases <- table_occ(
    clinic_intersect,
    "disease",
    unique(sort((
        clinic_intersect$disease
    )))
)
levels <- tab_diseases[as.numeric(tab_diseases) >= 5]

tab_gender <- table_occ(
    clinic_intersect,
    "gender",
    unique(sort((
        clinic_intersect$gender
    )))
)
```

# Indivduals
```{r ind}
Reduce(cbind, res$Y) %>%
    set_colnames(paste0(rep(names(res$Y), each = ncomp), ": Dim.", seq(ncomp))) %>%
    t() %>%
    corrplot(is.corr = FALSE, col = colorRampPalette(colors_ind)(100))

plot_ind0 <- function(
    x,
    colors = get_colors(),
    no_overlap = TRUE,
    text = FALSE,
    i_block = n
) {
    if (text) {
        no_overlap <- FALSE
    }
    plot_ind(
        res,
        i_block = i_block,
        cex_main = 30,
        cex_lab = 20,
        no_overlap = no_overlap,
        resp = as.data.frame(clinic_intersect[, x])[[1]],
        response_name = str_to_title(x),
        text = text,
        colors = colors
    )
}

plot_ind0("disease", i_block = 1, text = FALSE)

clinic_intersect <- mutate(
    clinic_intersect,
    diseases = case_when(
        !str_detect(
            disease,
            paste(replace_parenthesis(names(levels)), collapse = "|")
        ) ~ "Others",
        TRUE ~ disease
    )
)

colors <- c(
    rgb(255 / 255, 0 / 255, 0 / 255, 0.5),
    rgb(255 / 255, 204 / 255, 0 / 255, 0.5),
    rgb(0 / 255, 255 / 255, 0 / 255, 0.5),
    rgb(102 / 255, 153 / 255, 255 / 255, 0.5),
    rgb(204 / 255, 51 / 255, 255 / 255, 0.5),
    rgb(153 / 255, 153 / 255, 30 / 255, 0.5),
    rgb(0, 0, 0, 0.5)
)
# toRGB(c(pal_ucscgb()(7)[-2], "black"), 0.5)

plot_ind0("diseases", colors = get_colors(), text = TRUE)
```

# Biplot
```{r biplot}
ctr <- RGCCA:::get_ctr2(
    rgcca_res = res,
    compx = 1,
    compy = 2,
    i_block = 1,
    type = "loadings",
    n_mark = 100,
    remove_var = FALSE
) %>% mutate(
    top1 = ncol(blocks[[1]]) - (abs(X1) %>% row_number()) + 1,
    top2 = ncol(blocks[[1]]) - (abs(X2) %>% row_number()) + 1,
    name = colnames(blocks[[1]])
)
top_var <- bind_cols(
    ctr %>% arrange(top1) %>% head(10) %>% pull(name),
    ctr %>% arrange(top2) %>% head(10) %>% pull(name)
)
res_pca <- PCA(blocks[[1]], scale.unit = TRUE, ncp = 3, graph = FALSE)
res_pca$ind$coord <- res$Y[[1]]
res_pca$var$coord <- ctr[, seq(2)]
res_pca$var$contrib <- abs(ctr[, seq(2)])
res_pca$eig[seq(ncomp), 2] <- (res$AVE[[1]][[1]] * 100) %>% t() %>% t()
# res_pca$var$contrib[ pull(top_var, 2), "X1"] <- res_pca$var$contrib[ pull(top_var, 2), "X2"]
# theme_perso_2D(
#     fviz_pca_var(
#         res_pca,
#         col.var = "contrib",
#         repel = TRUE,
#         gradient.cols = colPers,
#         select.var = list(name = unlist(top_var))
#     )
# )

theme_perso_2D(
    fviz_pca_biplot(
        res_pca,
        repel = TRUE,
        col.var = "contrib",
        gradient.cols = c("gray", get_colors()[1]),
        # alpha.var = "contrib",
        col.ind = "gray",
        # palette = function (i) {c("red", "gray")},
        # pointsize = "cos2",
        mean.point = FALSE,
        select.var = list(name = unlist(top_var))
    ) +
        labs(fill = "Contribution")
)
```

# Bootstrap
```{r boot, eval = FALSE}
# eval <- rgcca_cv_k(res, validation = "loo")
n_boot <- 500
bb2 <- bootstrap(res, n_boot = n_boot)
file_boot <- "bootstrap_still_rna_clinic.RData"
use_data(bb2, file = file_boot, overwrite = TRUE)
load(file.path(path1, file_boot))
top_var <- get_bootstrap(bb, type = "loadings")
top_genes <- top_var %>%
    data.frame() %>%
    mutate(name = rownames(top_var)) %>%
    tibble() %>%
    arrange(desc(bootstrap_ratio)) # %>%
    # filter(adjust.pval <= 0.05)
# plot_bootstrap_2D(df_b = top_var, y = "occurences")
    arrange(top_genes, desc(mean)) %>% head(30) %>% plot_bar(cex = 7)
plot_bootstrap_1D(df_b = top_var, x = "bootstrap_ratio", display_bar = FALSE, y = "sign", n_mark = 100)
plot_bootstrap_1D(df_b = top_var, x = "occurences", display_bar = FALSE, y = "occurences")
```

# New version
```{r}
block_colors <- brewer.pal(n = 9, name = "Set1")
n_cores <- parallel::detectCores() - 2
ncomp <- 2
Y <- pull(blocks0[[n]], 1)
Y <- blocks0[[n]][, 1] %>% as.factor()

disj <- model.matrix(~ Y - 1) %>% 
  as.data.frame() %>%
  set_colnames(levels(Y)) %>% 
  set_rownames(rownames(blocks0[[n]]))

# fit <- rgcca(
#   blocks = blocks0[c(1, 3:4)],
#   ncomp = ncomp,
#   response = n
# )
# summary(fit)

# CV
ids <- caret::createDataPartition(
  Y,
  p = .75, 
  list = FALSE
)
training <- lapply(blocks0[c(1:2)], function(x) as.matrix(x)[ids, , drop = FALSE])
testing <- lapply(blocks0[c(1:2)], function(x) as.matrix(x)[-ids, , drop = FALSE])

cv_out <- rgcca_cv(
  blocks = training, 
  response = n,
  par_type = "ncomp",
  par_value = sapply(blocks0, NCOL),
  par_length = 10,
  prediction_model = "lda",
  validation = "kfold",
  k = 10, 
  n_run = 10,
  metric = "Balanced_Accuracy",
  n_cores = n_cores,
  NA_method = "na.ignore"
)
summary(cv_out)
plot(cv_out, cex = 2)
fit0 <- rgcca(cv_out)
rgcca_res_boot$call$blocks[[response]] <-
  as.matrix(as.factor(rgcca_res_boot$call$blocks[[response]][, 1]))
colnames(rgcca_res_boot$call$blocks[[response]]) <- 
  colnames(raw_rgcca$call$blocks[[response]])
pred_train <- rgcca_predict(res4, blocks_test = training, prediction_model = "lda")
pred_test <- rgcca_predict(res4, blocks_test = testing, prediction_model = "lda")
projection <- rgcca_transform(fit0, blocks_test = testing)

# Permutation
perm_out <- rgcca_permutation(
  blocks = A,
  connection = C,
  par_type = "tau",
  par_length = 10,
  n_cores = n_cores,
  n_perms = 10,
  n_mark = 20
)
summary(perm_out)
plot(perm_out)

# Plots
plot(
  res1,
  type = "weight",
  comp = 1,
  display_order = TRUE,
  cex = 2,
  n_mark = 15,
  var_colors = block_colors,
  block = 2:4,
  digits = 2,
  width_title = 50
)

plot(
  res4,
  block_cor = blocks0[c(3:4)],
  type = "loadings",
  comp = 1,
  block = 1:2,
  display_blocks = 1:2,
  cex = 2,
  var_colors = block_colors[c(2, 3)],
  var_shapes = 20,
  n_mark = 15,
  repel = TRUE,
  width_text = 50
)
fit$AVE
plot(
  fit,
  type = "ave",
  comp = 1,
  cex = 2,
  AVE_colors = brewer.pal(n = 9, name = "Set1")
)
fit$Y
plot(
    fit,
    type = "sample",
    block = 2:3,
    comp = 1,
    resp = Y,
    repel = TRUE,
    cex = 1,
    max.overlaps = 50,
    show_sample_names  = FALSE
)
plot(
    res2,
    type = "biplot",
    block = 4,
    comp = 1:2,
    repel = TRUE,
    resp = Y,
    cex = 2,
    show_arrow = FALSE,
    show_sample_names = FALSE,
    n_mark = 10,
    sample_shapes = 20,
    var_shapes = 20,
    sample_colors = row_col,
    var_colors = "gray50",
    force = 100
)

plot(
  res2,
  type = "cor_circle",
  comp = 1:2,
  block = 4,
  display_blocks = 2:3,
  cex = 2,
  var_colors = block_colors[c(1, 2)],
  var_shapes = 20,
  n_mark = 10,
  repel = TRUE,
  force = 100
)

plot(
    res4,
    type = "cor_circle",
    block = 2,
    comp = 1:2,
    cex = 2,
    var_colors = block_colors[5],
    var_shapes = 20,
    n_mark = 5,
    repel = TRUE,
    force = 100,
    display_blocks = 1,
    block_cor = list( A = blocks0[[3]])
)

plot(
    res6,
    type = "cor_circle",
    comp = 1:2,
    block = 2,
    display_blocks = 1:4,
    cex = 2,
    var_colors = get_colors()[c(2, 3, 5, 1)],
    var_shapes = 20,
    n_mark = 3,
    repel = TRUE,
    force = 1000,
    block_cor = c(Groups = list(disj), blocks0[2:4]),
    max.overlaps = 100
)

plot(
    res1,
    type = "cor_circle",
    comp = 1:2,
    block = 5,
    cex = 2,
    var_colors = get_colors()[c(2, 3, 5, 1)],
    var_shapes = 20,
    n_mark = 3,
    repel = TRUE,
    width_text = 50,
    force = 1000
)

plot(
    res2,
    block_cor = c(Group = list(disj), blocks0[c(2:4)]),
    type = "cor_circle",
    comp = 1:2,
    block = 1,
    display_blocks = 1:4,
    cex = 2,
    var_colors = get_colors()[c(2, 3, 5, 1)],
    var_shapes = 20,
    n_mark = 5,
    repel = TRUE,
    width_text = 50,
    force = 1000
)

# Bootstraps
boot_out0 <- rgcca_bootstrap(res2, n_boot = 500, n_cores = n_cores)
boot_out <- rgcca_bootstrap(res2, n_boot = 500, n_cores = n_cores, prediction_model = "lda")
boot_out3 <- rgcca_bootstrap(res4, n_boot = 500, n_cores = n_cores, prediction_model = "lda", block_cor = blocks0[2:4], block = 2)
summary(boot_out, block = 1:3, ncomp = 1)
plot(
    boot_out,
    type = "weight",
    block = 2:4,
    comp = 1,
    cex = 2,
    show_stars = FALSE,
    colors = block_colors[c(2, 3, 1)],
    width_title = 30,
    width = 100,
    n_mark = 20,
    label_x = "value",
    colour_text = "gray60"
)
plot(
    boot_out2,
    type = "loadings",
    comp = 1,
    cex = 2,
    show_stars = FALSE,
    colors = block_colors[c(2, 3, 1)],
    width_title = 30,
    width = 25,
    n_mark = 5,
    label_x = "value",
    colour_text = "gray60",
    block = 1:3
)
# Supervised
A2 <- c(A, as.data.frame(lab) %>% set_rownames(rownames(A[[1]])) %>% list(Democracy = .))
n <- length(A2)
fit2 <- rgcca(
  blocks = A2,
  response = n,
  ncomp = c(rep(ncomp, 3), 1)
)

# Stability
fit1 <- rgcca(
  blocks = blocks,
  sparsity = c(.2, .2, 0),
  response = 3,
  ncomp = ncomp
)
fit_stab <- rgcca_stability(
  fit1,
  keep = vapply(
    fit1$a, function(x)
    mean(x != 0),
    FUN.VALUE = 1.0
  ),
  n_boot = 100,
  verbose = TRUE,
  n_cores = n_cores
)
summary(fit_stab)
plot(fit_stab, var_colors = block_colors, type = "loadings")
```

