---
title: "rna"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rna}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Setup
```{r setup}
library(multiAnalysis)
# set_analysis(block_name = "still_manif", type = "qual")
set_analysis(block_name = "still_treatment", type = "qual")
data("rna")
row_names <- intersect(rownames(rna), rownames(blocks))
blocks <- list.map(list(blocks, rna), f(i) ~ filter(i, rownames(i) %in% row_names))
rna <- blocks[[2]]
clinic_intersect <- blocks[[1]]
# treat <- attributes(clinic_intersect)$codes %>%
#     filter(str_detect(item_name, "^response_to")) %>%
#     filter(str_detect(group_name, "response_to_treatments")) %>%
#     pull(item_name)
# vars <- c("mucocutaneous", "musculoskeletal")
# vars <- c("Urticaria", "Myocarditis")
vars <- colnames(clinic_intersect)[-3]
l_volcano <- list()
l_enrich <- list()
library(enrichR)
setEnrichrSite("Enrichr")
# listEnrichrDbs()$libraryName[listEnrichrDbs()$libraryName %>% grepl("orphanet", ., ignore.case = TRUE)]
dbs <- c("GO_Molecular_Function_2021", "GO_Biological_Process_2021", "Orphanet_Augmented_2021", "WikiPathway_2021_Human", "MSigDB_Hallmark_2020", "Reactome_2022")
i <- 1
```

# Descriptive stats
```{r, eval = FALSE}
exps <- clinic_intersect %>%
    mutate(
        exp = will_have_a_second_visit,
        second = factor(
            evolution_of_previous_flare_since_the_last_immun_aid_visit,
            labels = c("Complete", "No", "Partial")
        ) %>% fct_relevel(c("Complete", "Partial", "No")),
        followup = factor(
            evolution_of_the_disease_since_the_last_visit,
            labels = c("Complete\n+flare", "Complete", "Partial")
        ) %>% fct_relevel(c("Complete", "Complete\n+flare", "Partial"))
    ) %>%
    select(
        c(
            "exp",
            "second",
            "followup"
        )
    )

manif_vars <- attributes(clinic_intersect)$codes %>%
    filter(group_name == "is_impacted") %>%
    pull(item_name)
manif_df <- select(clinic_intersect, manif_vars) %>%
    cbind(rna, .) %>%
    tibble() %>%
    mutate(cl = ) %>%
    select(all_of(manif_vars))
list.map(
    manif_vars, f(i) ~ {
        manif_df %>%
            pull(i) %>%
            fct_count()
    }
) %>%
    Reduce(function(i, j) left_join(i, j, by = "f"), .) %>%
    set_colnames(c("Impacted", str_to_title(manif_vars))) %>%
    slice(2, 1, 3) %>%
    kable0()
select(manif_df, mucocutaneous, musculoskeletal) %>% plot_alluvial()

select(clinic_intersect, treat) %>%
    lapply(fct_count) %>%
    Reduce(function(i, j) left_join(i, j, by = "f"), .) %>%
    set_colnames(c("Response", vars)) %>%
    slice(3, 2, 1, 4) %>%
    kable0()
select(clinic_intersect, treat) %>%
    lapply(function(i) {
        fct_collapse(i, Yes = c("No", "Partial", "Total")) %>%
            fct_count()
    }) %>%
    Reduce(function(i, j) left_join(i, j, by = "f"), .) %>%
    set_colnames(c("Treatment", vars)) %>%
    mutate(Treatment = c("Yes", "No")) %>%
    kable0()

bind_rows(
    count(exps, exp, second) %>% set_colnames(c("exp", "var", "n")),
    count(exps, exp, followup) %>% set_colnames(c("exp", "var", "n"))
) %>%
    mutate(exp = c("No", "Yes", rep("", 3), "No", rep("", 2), "Yes", rep("", 2))) %>%
    set_colnames(c("Experienced", "Response", "n")) %>%
    select(c("Response", "Experienced", "n")) %>%
    kable0() %>%
    pack_rows("Second visit", 1, 5) %>%
    pack_rows("Follow-up", 6, 11)

count(exps, exp, second, followup) %>%
    ggplot(aes(y = n, axis1 = second, axis2 = exp, axis3 = followup)) +
    geom_alluvium(aes(fill = exp), width = 0.5, knot.pos = 0) +
    geom_stratum(width = 0.5, fill = "black", color = "grey") +
    geom_text(
        stat = "stratum",
        color = "white",
        aes(label = after_stat(stratum)),
        size = 8
    ) +
    scale_x_discrete(
        limits = c("Second visit", "Experienced", "Follow-up"),
        expand = c(.05, .05)
    ) +
    scale_fill_manual(values = get_colors()[seq(2)]) +
    scale_y_continuous(breaks = seq(0, 40, 5), minor_breaks = seq(36)) +
    labs(y = "n") +
    theme_minimal() +
    theme(legend.position = "none", axis.ticks.x = element_blank()) %>%
    theme_perso0(1.5, show_axis = FALSE)

count(exps, exp, followup) %>%
    ggplot(aes(
        x = exp,
        y = followup,
        size = n,
        colour = n
    )) +
    geom_text(aes(label = n)) +
    scale_size(range = c(2, 15), limits = c(0, 25), guide = FALSE) +
    scale_color_gradientn(colours = colors_ind, limits = c(0, 25)) +
    theme_minimal() %>%
    theme_perso0(1.5, show_axis = FALSE) +
    theme(axis.ticks = element_blank()) +
    xlab("Experienced") +
    ylab("Follow-up")
```

# DEA
```{r}
## Naive vs. experienced
# exp <- clinic_intersect %>%
#     select(c("will_have_a_second_visit", all_of(treat))) %>%
#     set_colnames(c("Experienced", vars))
#
# df <- cbind(rna, exp) %>%
#     tibble() %>%
#     filter(Experienced == "Yes") %>%
#     mutate(cl = ifelse(!is.na(Prednisolone), "Yes", "No") %>% factor()) %>%
#     select(-c("Experienced", all_of(vars)))

## Impacted organ
for (var in vars) {
    # var <- vars[i]
    filename_top_genes <- file.path(path_out, paste0("top_genes_", tolower(var), ".temp.tsv"))
    
    df <- pull(clinic_intersect, var) %>%
        as.factor() %>%
        fct_recode(Yes = "1", No = "0") %>%
        cbind(rna, cl = .) %>%
        tibble()

    # res <- select(exp,-seq(11680)) %>% calculate_test(method = "wilcox")
    # res0 <- calculate_test(df, method = "wilcox")
    data_path <- file.path(get_golem_wd(), "data", paste0("de_", tolower(var), ".RData"))
    # save(res0, file = data_path)
    load(data_path)
    res <- differential_analysis(res0)

    get_top(res, n = 100) %>%
        write_tsv(file = filename_top_genes)
    # 1.2, 0.05, 0.8, 0.01
    # 0.8, 0.05, 0.8, 0.01
    # 0.8, 0.01, 1.2, 0.01
    # 0.8, 0.05, 0.8, 0.01
    # 0.8, 0.01, 1.2, 0.01
    (volcano <- get_top(res, n = 10) %>% volcano_plot(res, ., var, "none", 1.7) + xlab("") + ylab(""))
    l_volcano <- list.append(l_volcano, volcano)
}
```

# Enrichment
```{r, eval = FALSE}
for (var in vars) {
    top_genes <- read_tsv(filename_top_genes)

    ## Enrichr
    enriched <- pull(top_genes, name) %>%
        enrichr(dbs)
    p <- list.map(
        enriched,
        f(i, j) ~ plot_enrich(i, n = 20, title = str_replace_all(dbs[j], "_", " "))
    )
    p_enrich <- plot_grid(
        plotlist = p,
        nrow = 2,
        ncol = 3,
        align = "hv"
    )
    save_tiff(p_enrich, file.path(path_img, paste0("enrichment_", tolower(var))), 8000, 4000)
    l_enrich <- list.append(l_enrich, p)
    # l_enrich[[i]] <- p
    # i = i + 1
}

# vars <- c("Mucocutaneous", "Musculoskeletal", "Urticaria", "Myocarditis")
p_enrich_biol <- list.map(l_enrich, f(i, j) ~ pluck(i, 5) + ggtitle(vars[j]))
p_enrich <- plot_grid(
    plotlist = c(p_enrich_biol[seq(2)], list(NULL), p_enrich_biol[3:4]),
    nrow = 2,
    ncol = 3,
    align = "hv"
)
save_tiff(p_enrich, file.path(path_img, paste0("enrichment_hallmark_treat")), 8000, 4000)

(p_volcano <- plot_grid(
    plotlist = c(l_volcano[seq(2)], list(NULL), l_volcano[3:4]),
    nrow = 2,
    ncol = 3,
    align = "hv"
))
# 3000, 2000
save_tiff(p_volcano, file.path(path_img, "volcano_treat"), 8000, 4000)
```

```{r, eval = FALSE}
# ClusterProfiler
# TODO: fix
library(clusterProfiler)
organism <- "org.Hs.eg.db"
library(organism, character.only = TRUE)
gene_list <- pull(res, "log2fc") %>%
    as.double() %>%
    setNames(res$name) %>%
    na.omit() %>%
    sort(decreasing = TRUE)
gse <- gseGO(gene_list, ont = "All", OrgDb = organism, keyType = "SYMBOL")
dotplot(gse, showCategory = 10)

kegg_genes <- bitr(top_genes$name, fromType = "SYMBOL", toType = c("ENTREZID"), OrgDb = "org.Hs.eg.db")
```

