---
title: "SOM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SOM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Setup
```{r setup}
library(multiAnalysis)
set.seed(123)
type <- "qual"
set_analysis(block_name = "clinic_still_processed", to_remove = c("1007", "1014"), type = type)
hc_metric <- "spearman"
# blocks <- blocks[[1]]
n_run <- 1e4
MAX_CLUSTERS <- 10
hc_method <- 1
cols <- function(a = 1) {
    c(rgb(77 / 250, 175 / 250, 75 / 250, a), rgb(150 / 250, 80 / 250, 150 / 250, a), rgb(1, 0.5, 0, a), rgb(1, 40 / 250, 45 / 250, a), rgb(0 / 250, 120 / 250, 180 / 250, a), rgb(100 / 250, 50 / 250, 75 / 250, a))
}
# c(rgb(77/250, 175/250, 75/250, a),rgb(77/250, 175/250, 75/250, a),rgb(150/250, 80/250, 150/250, a), rgb(150/250, 80/250, 150/250, a)) #, rgb(1, 40/250, 45/250, a), rgb(1, 0.5, 0, a), rgb(0/250, 120/250, 180/250, a))

col_grp <- function(x = som_clusters, a = 1) {
    x <- as.factor(x)
    levels(x) <- cols(a)
    return(as.vector(x))
}
```

# Data preparation
```{r}
res_scaled_na <- scale0(blocks, "zscore")
res_scaled <- res_scaled_na
res_scaled[is.na(res_scaled)] <- 0
```

# Modelling
```{r, eval = FALSE}
n_cores <- parallel::detectCores() - 2
som_grid <- somgrid(
    xdim = 3,
    ydim = 3,
    toroidal = TRUE,
    topo = "hexagonal"
)
model <- "som_model2"
assign(
  model,
  som(
    res_scaled_na,
    grid = som_grid,
    rlen = n_run,
    maxNA.fraction = 100,
    dist.fcts = "tanimoto"
  ),
  envir = .GlobalEnv
)
```


```{r}
som_model <- xyf(
    as.matrix(res_scaled_na),
    classvec2classmat(Y),
    grid = som_grid,
    rlen = n_run,
    maxNA.fraction = 100,
    # dist.fcts = "tanimoto",
    cores = n_cores
  )
beepr::beep()
# path <- file.path(golem::get_golem_wd())
# file_path <- file.path(path, "data", paste0(model, ".RData"))
# save(som_model_qual4, file = file_path)
# load(file_path)
# som_model <- get(model)
# plot(som_model, type = "changes")

som_inds <- som_model$unit.classif %>% set_names(rownames(blocks))
print(sapply(seq(max(som_inds)), function(x) names(som_inds[som_inds == x])))
(df <- som_inds %>%
    as.factor() %>%
    fct_infreq() %>%
    fct_count()
)
```

# Clustering
```{r}
# Data preparation
som_codes <- som_model$codes[[1]]
rownames(som_codes) <- rownames(som_codes) %>% gsub("V", "N", .)

# Clustering for the samples
res_dist <- get_dist(som_codes, stand = FALSE, method = hc_metric)
n <- nrow(som_codes) - 2
if (MAX_CLUSTERS > n) {
    MAX_CLUSTERS <- n
}
classif <- getClassif(hc_method, MAX_CLUSTERS, som_codes, res_dist)
cls <- getClusterPerPart(MAX_CLUSTERS, classif)
cl_summary <- get_summary(res_dist, cls, MAX_CLUSTERS, k = 2)
cl_summary
k <- which.max(cl_summary$`Silhouette index`) + 1
lapply(
    2:MAX_CLUSTERS,
    function(i) plot_silhouette0(res_dist, cls, i)
) %>%
    plot_grid(
        plotlist = .,
        align = "vh",
        labels = paste("k =", 2:MAX_CLUSTERS),
        hjust = 0,
        nrow = 2,
        ncol = 3
    )

# Variable contribution
100 * getCtrVar(k, cls[[k - 1]], som_codes)
ctr <- getDiscriminantVariables(k, cls[[k - 1]], som_codes, ncol(som_codes))
GimmeMyPlot::plot_bar(
    select(ctr, 1),
    n_max = 10,
    digits = 2,
    threshold = 0,
    abs = TRUE,
    colour = c("#99000D", "gray"),
    title = ".",
    label_x = "name",
    width_text = 25
)

# res0 <- pvclust(
#   t(som_codes),
#   method.hclust = hc_method,
#   method.dist = "euclidian",
#   use.cor = "pairwise.complete.obs",
#   nboot = n_boot,
#   parallel = TRUE
# ) %>% suppressWarnings()
# plot_dendrogram(res0, k = k, color = colors_k)
som_clusters <- cls[[k - 1]]
# som_clusters <- append(som_clusters, 3, after = 4)

# som_clusters <- read.csv2(file.path(path_out, "clusters0.temp.tsv"))$cl0
ind_clusters <- som_clusters[som_inds] %>% set_names(names(som_inds))
ind_clusters %>%
    as.factor() %>%
    fct_infreq() %>%
    fct_count()

# Chi-test
# if (type == "qual") {
#   chi2(som_clusters, som_codes)
#   chi2(ind_clusters, blocks)
# }
```

```{r, eval = FALSE}
# Disease per groups
names(ind_clusters) <- disease
lapply(seq(k), function(i) {
    ind_clusters[ind_clusters == i] %>%
        names() %>%
        fct_infreq() %>%
        fct_count() %>%
        filter(n > 0) %>%
        data.frame(., i) %>%
        # set_colnames(rep("", 2))
        set_colnames(c("Disease", "N/cluster", "Cluster"))
}) %>%
    # set_names(paste("Cluster", seq(k)))
    list.stack()

# names(ind_clusters) <- rownames(res_scaled_na)
lapply(seq(k), function(i) ind_clusters[ind_clusters == i])

# Quality per samples
ind_dist <- get_dist(res_scaled, stand = FALSE, method = hc_metric)
ind_cls <- list.map(cls, f(i) ~ i[som_inds])
ind_summary <- get_summary(ind_dist, ind_cls, MAX_CLUSTERS, k = 2)
ind_summary
lapply(
    2:MAX_CLUSTERS,
    function(i) plot_silhouette0(ind_dist, ind_cls, i)
) %>%
    plot_grid(
        plotlist = .,
        align = "vh",
        labels = paste("k =", 2:MAX_CLUSTERS),
        hjust = 0,
        nrow = 2,
        ncol = 3
    )

(centers_k <- getDistPerVariable0(som_codes, som_clusters))
centers <- lapply(cls, function(i) getDistPerVariable0(som_codes, i))
getClassif(2, MAX_CLUSTERS - 1, som_codes, res_dist, centers = centers)
# centers <- lapply(cls, function(i) calculate_medoid(som_codes, res_scaled, i))
# With the raw data
getDistPerVariable0(blocks, som_inds) %>% getDistPerVariable0(som_clusters)
```

# Heatmap
```{r, eval = FALSE}
# Clustering for the variables
if (hc_method > 2) {
    col_dist <- t(som_codes) %>%
        get_dist(stand = FALSE, method = hc_metric)
    col_classif <- hclust(col_dist, method = getClassifType(hc_method))
    col_cls <- getClusterPerPart(MAX_CLUSTERS, col_classif)
    col_summary <- get_summary(col_dist, col_cls, MAX_CLUSTERS, k = 2)
    col_summary
    k_col <- which.max(col_summary$`Silhouette index`) + 1
    lapply(
        2:MAX_CLUSTERS,
        function(i) plot_silhouette0(col_dist, col_cls, i)
    ) %>%
        plot_grid(
            plotlist = .,
            align = "vh",
            labels = paste("k =", 2:MAX_CLUSTERS),
            hjust = 0,
            nrow = 2,
            ncol = 3
        )

    pheatmap(
        scale0(som_codes, "minmax"),
        color =  colorRampPalette(colors_ind)(100),
        angle_col = 315,
        na_col = "black",
        border_color = NA,
        # annotation_col = my_sample_col,
        cluster_rows = classif,
        cluster_cols = col_classif,
        cutree_rows = k,
        cutree_cols = k_col
    )
}
```

# Code plots
```{r}
dist_neighbours <- plot(som_model, type = "dist.neighbours")
quality <- plot(som_model, type = "quality")
par(mfrow = c(2, 2))
col_func <- function(i) colorRampPalette(c("blue", "grey90", "red"))
plot(som_model, type = "counts", shape = "straight", border = NA, palette.name = col_func(max(pull(df, n))))
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")
plot(som_model, type = "dist.neighbours", shape = "straight", border = NA, palette.name = col_func(max(dist_neighbours)))
print_stats0(dist_neighbours, 2)
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")
plot(som_model, type = "quality", shape = "straight", border = NA, palette.name = col_func(max(quality)))
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")
print_stats0(quality, 2)
names(ind_clusters) <- rownames(res_scaled_na)
# plot(som_model, type = "changes")
par(mfrow = c(1, 1))

plot(
    som_model,
    cex = 0.7,
    type = "mapping",
    labels = names(ind_clusters),
    col = disease0,
    bg = col_grp(a = 0.25),
    shape = "straight",
    border = NA
)
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")

plot(
    som_model,
    cex = 0.7,
    type = "mapping",
    labels = rownames(facs0),
    col = disease0,
    bg = col_grp(a = 0.25),
    shape = "straight",
    border = NA
)
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")

plot(
    som_model,
    cex = 0.7,
    type = "mapping",
    labels = disease1,
    col = disease0,
    bg = col_grp(a = 0.25),
    shape = "straight",
    border = NA
)
add.cluster.boundaries(som_model, som_clusters, lwd = 5, col = "white")

cex <- 1.5
tiff(
      "temp.tiff",
      units = "px",
      width = 2000 * cex,
      height = 2000 * cex,
      res = 300
    )
plot(
    som_model,
    type = "codes",
    palette.name = function(i) {
                colorRampPalette(GimmeMyPlot:::palette_discrete2())(ncol(facs0))
      },
    codeRendering = "segments",
    whatmap = 1,
    shape = "straight",
    border = NA,
    bg = col_grp(a = 0.25)
)
# add.cluster.boundaries(som_model, som_clusters, lwd = 20, col = "white")
dev.off()

# plot(som_model, type = "codes", palette.name = rainbow, codeRendering = "segments")
# plot(som_model, type = "codes", palette.name  = function(i) get_colors()[seq(14)], codeRendering = "segments")

# write.csv2(as.data.frame(ind_clusters), "clusters_som2.temp.tsv")
```
